// All birds used in the quiz, grouped by category (see
// birdCategories.js). Mirrors species.js's schema exactly — see that
// file for what each field means (images, weight, habitat, activity,
// rarity, native, differentiator, features).
//
// A couple of species have photos spread across two folders on disk
// (e.g. huldue lives partly under fugle/duer and partly under
// fugle/spurvefugle) — that's just where the files landed, not a
// taxonomic split, so their `images` arrays pull from both paths.

const SPECIES = [
  // --- Duer (pigeons & doves) ---
  {
    id: "huldue",
    category: "duer",
    name_da: "Huldue",
    name_en: "Stock dove",
    latin: "Columba oenas",
    images: [
      "/images/fugle/duer/huldue_1.jpg",
      "/images/fugle/spurvefugle/huldue_2.jpg",
      "/images/fugle/spurvefugle/huldue_3.jpg",
    ],
    weight: "260–330 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Mindre end ringduen, uden hvide halspletter eller vingebånd — har i stedet to korte, utydelige mørke bånd på vingen.",
    features: [
      "Smaller and plainer than the woodpigeon, with no white neck patch or white wing bar",
      "Blue-grey overall with a subtly iridescent green-purple neck sheen",
      "Nests in tree holes, old buildings, and sometimes rabbit burrows — unlike the tree-nesting woodpigeon",
      "Often overlooked among flocks of woodpigeons",
    ],
  },
  {
    id: "ringdue",
    category: "duer",
    name_da: "Ringdue",
    name_en: "Common woodpigeon",
    latin: "Columba palumbus",
    images: ["/images/fugle/duer/ringdue_1.jpg", "/images/fugle/duer/ringdue_2.jpg", "/images/fugle/duer/ringdue_3.jpg"],
    weight: "480–550 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Danmarks største due — hvide pletter på begge sider af halsen og et tydeligt hvidt bånd på vingen i flugt.",
    features: [
      "Denmark's largest and most common dove, plump and grey with a pinkish breast",
      "White patches on either side of the neck, and a bold white bar across each wing in flight",
      "Common in gardens, parks, farmland, and woodland alike",
      "Loud, rhythmic \"coo-COO-coo, coo-coo\" song",
    ],
  },
  {
    id: "tyrkerdue",
    category: "duer",
    name_da: "Tyrkerdue",
    name_en: "Eurasian collared dove",
    latin: "Streptopelia decaocto",
    images: ["/images/fugle/duer/tyrkerdue_1.jpg", "/images/fugle/duer/tyrkerdue_2.jpg"],
    weight: "150–220 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Slank, sandfarvet due med en tynd, sort halvring i nakken — mindre og lysere end ringduen.",
    features: [
      "Slim, pale sandy-buff dove with a thin black half-collar on the back of the neck",
      "Smaller and paler than the woodpigeon, with no white wing bars or neck patches",
      "Strongly tied to towns, gardens, and farms — rarely far from human settlement",
      "Spread across almost all of Europe from the Balkans during the 20th century",
    ],
  },

  // --- Dykænder (diving ducks) ---
  {
    id: "amerikanskskarveand",
    category: "dykaender",
    name_da: "Amerikansk skarveand",
    name_en: "Ruddy duck",
    latin: "Oxyura jamaicensis",
    images: ["/images/fugle/dykaender/amerikanskskarveand_1.jpg", "/images/fugle/dykaender/amerikanskskarveand_2.jpg"],
    weight: "300–800 g",
    habitat: "soeer",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Hannen har et klarblåt næb, sort isse og en rustrød krop — holder ofte den stive hale opret som et sejl.",
    features: [
      "Small, stocky diving duck; breeding males have a bright sky-blue bill, black cap, and rich chestnut body",
      "Often holds its stiff tail cocked upright like a little sail",
      "Native to North America; an invasive species in Europe, actively controlled due to hybridisation risk with the endangered white-headed duck",
      "Very rare in Denmark, seen mainly as an escapee from wildfowl collections",
    ],
  },
  {
    id: "bjergand",
    category: "dykaender",
    name_da: "Bjergand",
    name_en: "Greater scaup",
    latin: "Aythya marila",
    images: ["/images/fugle/dykaender/bjergand_1.jpg", "/images/fugle/dykaender/bjergand_2.jpg"],
    weight: "800–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Ligner en troldand, men hannen har en grøn (ikke violet) glans på hovedet og mangler toppen i nakken.",
    features: [
      "Similar to the tufted duck but without its drooping head tuft",
      "Males have a rounded head with a green (not purple) gloss, and a pale grey (not white) back",
      "A mainly coastal, saltwater diving duck, especially in winter",
      "Forms large rafts offshore, often mixed with other diving ducks",
    ],
  },
  {
    id: "ederfugl",
    category: "dykaender",
    name_da: "Ederfugl",
    name_en: "Common eider",
    latin: "Somateria mollissima",
    images: [
      "/images/fugle/dykaender/ederfugl_1.jpg",
      "/images/fugle/dykaender/ederfugl_2.jpg",
      "/images/fugle/dykaender/ederfugl_3.jpg",
    ],
    weight: "1.2–2.8 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Danmarks tungeste and — hannen er sort og hvid med et grønligt nakkeparti og en kileformet næb-/pandeprofil.",
    features: [
      "Denmark's heaviest duck, and a classic sight along the coast",
      "Males are boldly black-and-white with a pale green patch on the nape",
      "Distinctive wedge-shaped head profile, where the bill blends smoothly into the sloping forehead",
      "Females are soft brown, closely barred, and provide the famous soft down used to line their nests",
    ],
  },
  {
    id: "floejlsand",
    category: "dykaender",
    name_da: "Fløjlsand",
    name_en: "Velvet scoter",
    latin: "Melanitta fusca",
    images: ["/images/fugle/dykaender/floejlsand_1.jpg", "/images/fugle/dykaender/floejlsand_2.jpg"],
    weight: "1.2–2 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Sortand med et tydeligt hvidt vingespejl og en lille hvid plet under øjet — sortanden er helt sort uden hvidt.",
    features: [
      "Large, all-dark sea duck with a bold white patch on the wing, visible at rest and in flight",
      "Males have a small white crescent below the eye and a bulbous, orange-marked bill",
      "Dives for mussels and other shellfish in coastal waters",
      "A winter visitor, often seen in flocks well offshore",
    ],
  },
  {
    id: "havlit",
    category: "dykaender",
    name_da: "Havlit",
    name_en: "Long-tailed duck",
    latin: "Clangula hyemalis",
    images: ["/images/fugle/dykaender/havlit_1.jpg", "/images/fugle/dykaender/havlit_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hannen har meget lange, spidse halefjer, og fjerdragten skifter mellem overvejende hvid vinter- og mørk sommerdragt.",
    features: [
      "Males have remarkably long, needle-like tail feathers, unique among Danish ducks",
      "Plumage pattern reverses between seasons — mostly white in winter, mostly dark in summer",
      "Small, round-headed sea duck, diving to considerable depths for molluscs",
      "A noisy winter visitor, with a yodelling call often heard from rafts far offshore",
    ],
  },
  {
    id: "hvinand",
    category: "dykaender",
    name_da: "Hvinand",
    name_en: "Common goldeneye",
    latin: "Bucephala clangula",
    images: ["/images/fugle/dykaender/hvinand_1.jpg", "/images/fugle/dykaender/hvinand_2.jpg"],
    weight: "700–1200 g",
    habitat: "soeer",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Hannen har et rundt, mørkegrønt hoved med en tydelig, hvid rund plet foran det gule øje.",
    features: [
      "Males have a puffy, dark green head with a round white spot in front of the bright golden-yellow eye",
      "Compact, large-headed body shape, mostly white below and black above",
      "Wings make a loud whistling sound in flight, giving the species its Danish name (\"hvin\" = whistle)",
      "Nests in tree holes, including readily using nest boxes",
    ],
  },
  {
    id: "roedhovedetand",
    category: "dykaender",
    name_da: "Rødhovedet and",
    name_en: "Red-crested pochard",
    latin: "Netta rufina",
    images: [
      "/images/fugle/dykaender/roedhovedetand_1.jpg",
      "/images/fugle/dykaender/roedhovedetand_2.jpg",
      "/images/fugle/dykaender/roedhovedetand_3.jpg",
    ],
    weight: "900–1300 g",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: false,
    differentiator: "Hannen har et iøjnefaldende, rundt orange-rødt hoved og et klart rødt næb — helt unikt blandt de danske dykænder.",
    features: [
      "Males have a striking round, orange-red head and a bright red bill — unmistakable among Danish diving ducks",
      "Black breast and rear contrast with pale flanks",
      "Females are plain grey-brown with a pale cheek and a dark cap",
      "Originally a more southern/eastern species, now increasingly seen in Denmark",
    ],
  },
  {
    id: "sortand",
    category: "dykaender",
    name_da: "Sortand",
    name_en: "Common scoter",
    latin: "Melanitta nigra",
    images: ["/images/fugle/dykaender/sortand_1.jpg", "/images/fugle/dykaender/sortand_2.jpg"],
    weight: "800–1500 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Hannen er helt sort uden hvidt vingespejl — kendes fra fløjlsanden på den manglende hvide vingeplet.",
    features: [
      "Males are entirely black, with no white wing patch — unlike the velvet scoter",
      "A small yellow-orange patch on the upper bill is the male's only bright feature",
      "Females are dark brown with paler cheeks",
      "Forms large offshore rafts, especially during migration and winter",
    ],
  },
  {
    id: "taffeland",
    category: "dykaender",
    name_da: "Taffeland",
    name_en: "Common pochard",
    latin: "Aythya ferina",
    images: ["/images/fugle/dykaender/taffeland_1.jpg", "/images/fugle/dykaender/taffeland_2.jpg"],
    weight: "700–1100 g",
    habitat: "soeer",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Hannen har et rustrødt hoved og en grå (ikke sort) krop — rødhovedet and har et orange-rødt hoved og sort krop.",
    features: [
      "Males have a rounded chestnut-red head, black breast, and pale grey body",
      "Red eyes and a black-tipped grey bill",
      "Females are dull brown with a paler face",
      "A widespread diving duck on lakes and reservoirs",
    ],
  },
  {
    id: "troldand",
    category: "dykaender",
    name_da: "Troldand",
    name_en: "Tufted duck",
    latin: "Aythya fuligula",
    images: [
      "/images/fugle/dykaender/troldand_1.jpg",
      "/images/fugle/dykaender/troldand_2.jpg",
      "/images/fugle/dykaender/troldand_3.jpg",
    ],
    weight: "600–1000 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort-hvid and med en tydelig, slap fjertop hængende bagud fra issen — Danmarks mest almindelige dykand.",
    features: [
      "Denmark's most common diving duck — black above and on the breast, white on the flanks",
      "A drooping tuft of feathers hangs from the back of the male's head",
      "Bright golden-yellow eyes",
      "Common on lakes, ponds, and slow rivers, often diving in tight groups",
    ],
  },

  // --- Fasanfugle (gamebirds) ---
  {
    id: "agerhoene",
    category: "fasanfugle",
    name_da: "Agerhøne",
    name_en: "Grey partridge",
    latin: "Perdix perdix",
    images: ["/images/fugle/fasanfugle/agerhoene_1.jpg", "/images/fugle/fasanfugle/agerhoene_2.jpg"],
    weight: "300–400 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Rund, spraglet brun krop med en tydelig mørkebrun \"hestesko\"-plet på brystet — fasanen er langt større med lang hale.",
    features: [
      "Small, round-bodied gamebird with a rufous face and a dark chestnut horseshoe patch on the belly",
      "Grey-brown, finely barred plumage overall, with rufous streaking on the flanks",
      "Lives in coveys on farmland, nesting on the ground in field margins",
      "Explosive, whirring flush when disturbed, flying low and fast on rounded wings",
    ],
  },
  {
    id: "fasan",
    category: "fasanfugle",
    name_da: "Fasan",
    name_en: "Common pheasant",
    latin: "Phasianus colchicus",
    images: [
      "/images/fugle/fasanfugle/fasan_1.jpg",
      "/images/fugle/fasanfugle/fasan_2.jpg",
      "/images/fugle/fasanfugle/fasan_3.jpg",
    ],
    weight: "0.9–1.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Hannen har et iriserende grønblåt hoved og en meget lang, spids hale — hunnen er ensfarvet sandbrun og mindre.",
    features: [
      "Males are unmistakable: iridescent green-blue head, red face wattles, copper-brown body, and a very long pointed tail",
      "Females are mottled sandy-brown and far less showy, with a shorter tail than the male",
      "Common on farmland and woodland edges, largely due to continuous releases for hunting",
      "Prefers to run from danger, but explodes into a noisy, whirring flight if forced",
    ],
  },

  // --- Gæs (geese) ---
  {
    id: "blisgaas",
    category: "gaes",
    name_da: "Blisgås",
    name_en: "Greater white-fronted goose",
    latin: "Anser albifrons",
    images: ["/images/fugle/gaes/blisgaas_1.jpg", "/images/fugle/gaes/blisgaas_2.jpg"],
    weight: "2–3.2 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hvid pandeplet ved næbroden og sorte tværstriber på bugen — grågåsen mangler begge dele.",
    features: [
      "Grey-brown goose with a bold white blaze around the base of the bill",
      "Bold black barring across the belly, more so on older birds",
      "Orange legs and a pink bill",
      "A winter visitor from Arctic Russia, often in large flocks on farmland",
    ],
  },
  {
    id: "bramgaas",
    category: "gaes",
    name_da: "Bramgås",
    name_en: "Barnacle goose",
    latin: "Branta leucopsis",
    images: ["/images/fugle/gaes/bramgaas_1.jpg", "/images/fugle/gaes/bramgaas_2.jpg"],
    weight: "1.3–2.2 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Kridhvidt ansigt og sort hals/bryst i skarp kontrast — knortegåsen har en mørk, ikke hvid, ansigtsmaske.",
    features: [
      "Strikingly patterned: pure white face, black neck, breast and crown, and a silvery-grey barred body",
      "Smaller and more contrastingly patterned than the grey geese",
      "Highly social, often seen in large, dense flocks",
      "Numbers in Denmark have grown hugely in recent decades, both as a winter visitor and breeder",
    ],
  },
  {
    id: "canadagaas",
    category: "gaes",
    name_da: "Canadagås",
    name_en: "Canada goose",
    latin: "Branta canadensis",
    images: [
      "/images/fugle/gaes/canadagaas_1.jpg",
      "/images/fugle/gaes/canadagaas_2.jpg",
      "/images/fugle/gaes/canadagaas_3.jpg",
    ],
    weight: "3.5–6.5 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Danmarks største gås — sort hals med en bred, hvid \"hageklap\" op ad kinderne.",
    features: [
      "Denmark's largest goose, with a long black neck and a broad white cheek/chin strap",
      "Brown body with a paler breast, and a black bill, legs and feet",
      "Introduced from North America; now common and widespread on lakes, parks, and farmland",
      "Loud, honking calls, often given in flight in V-formation",
    ],
  },
  {
    id: "graagaas",
    category: "gaes",
    name_da: "Grågås",
    name_en: "Greylag goose",
    latin: "Anser anser",
    images: ["/images/fugle/gaes/graagaas_1.jpg", "/images/fugle/gaes/graagaas_2.jpg", "/images/fugle/gaes/graagaas_3.jpg"],
    weight: "3–3.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Ensfarvet gråbrun med et stort, orange næb — blisgås og sædgås har hvid pandeplet eller mørkere næb.",
    features: [
      "Denmark's most common wild goose, and ancestor of the domestic farmyard goose",
      "Uniform grey-brown plumage, pale forewing patch visible in flight, and a large orange bill",
      "Pink legs, distinguishing it from the dark-legged bean goose",
      "Breeds in Denmark and forms large flocks on farmland outside the breeding season",
    ],
  },
  {
    id: "knortegaas",
    category: "gaes",
    name_da: "Knortegås",
    name_en: "Brant goose",
    latin: "Branta bernicla",
    images: ["/images/fugle/gaes/knortegaas_1.jpg", "/images/fugle/gaes/knortegaas_2.jpg"],
    weight: "1.3–1.6 kg",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Danmarks mindste gås — mørk, næsten sort krop med en lille hvid halsplet, ingen hvid ansigtsmaske som bramgåsen.",
    features: [
      "Denmark's smallest goose — small, dark, and compact, almost duck-sized",
      "Sooty-black head, neck and breast with a small white neck patch (no white face mask)",
      "Strongly tied to coasts and mudflats, especially the Wadden Sea, feeding on eelgrass",
      "Travels in tight, fast-flying flocks",
    ],
  },
  {
    id: "kortnaebbetgaas",
    category: "gaes",
    name_da: "Kortnæbbet gås",
    name_en: "Pink-footed goose",
    latin: "Anser brachyrhynchus",
    images: ["/images/fugle/gaes/kortnaebbetgaas_1.jpg", "/images/fugle/gaes/kortnaebbetgaas_2.jpg"],
    weight: "2–3 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Kort, mørkt næb med et lyserødt bånd og lyserøde ben — sædgåsen har et længere, mørkere næb med orange bånd.",
    features: [
      "Small, dark-headed grey goose with a short, stubby dark bill marked with a pink band",
      "Pink legs — the clearest difference from the similar bean goose's orange legs",
      "A passage/winter visitor from Svalbard and Greenland, often in huge, noisy flocks",
      "Grazes on farmland, especially stubble fields and winter cereals",
    ],
  },
  {
    id: "nilgaas",
    category: "gaes",
    name_da: "Nilgås",
    name_en: "Egyptian goose",
    latin: "Alopochen aegyptiaca",
    images: ["/images/fugle/gaes/nilgaas_1.jpg", "/images/fugle/gaes/nilgaas_2.jpg"],
    weight: "1.5–2.3 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: false,
    differentiator: "Tydelig mørkebrun plet om øjet og en mørk plamage midt på det lyse bryst — ligner ingen af de øvrige gæs.",
    features: [
      "Distinctive dark brown patch around the eye and another blotch in the centre of the pale breast",
      "Pale sandy-brown body, pinkish legs, and a mostly pink-and-black bill",
      "Actually more closely related to shelducks than to true geese",
      "An invasive species in Europe, escaped from ornamental waterfowl collections; expanding in Denmark",
    ],
  },
  {
    id: "saedgaas",
    category: "gaes",
    name_da: "Sædgås",
    name_en: "Taiga bean goose",
    latin: "Anser fabalis",
    images: ["/images/fugle/gaes/saedgaas_1.jpg", "/images/fugle/gaes/saedgaas_2.jpg"],
    weight: "2.5–3.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Mørkt hoved og hals med et langt, sort-og-orange næb — kortnæbbet gås har et kortere næb med lyserødt bånd.",
    features: [
      "Dark brown head and neck, with a long bill patterned black with an orange band",
      "Orange legs, unlike the pink-footed goose's pink legs",
      "A winter visitor from northern Scandinavia and Russia, favouring farmland and wet meadows",
      "Generally shyer and found in smaller flocks than pink-footed or greylag geese",
    ],
  },

  // --- Måger (gulls) ---
  {
    id: "haettemaage",
    category: "maager",
    name_da: "Hættemåge",
    name_en: "Black-headed gull",
    latin: "Chroicocephalus ridibundus",
    images: ["/images/fugle/maager/haettemaage_1.jpg", "/images/fugle/maager/haettemaage_2.jpg"],
    weight: "200–400 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Danmarks mindste og mest almindelige måge — i sommerdragt med chokoladebrun (ikke sort) hætte.",
    features: [
      "Denmark's smallest and most common gull",
      "In breeding plumage, a chocolate-brown (not black) hood covering the head",
      "In winter, the hood is lost, leaving just a small dark spot behind the eye",
      "Red bill and legs; found equally on coasts, lakes, farmland, and in city parks",
    ],
  },
  {
    id: "sildemaage",
    category: "maager",
    name_da: "Sildemåge",
    name_en: "Lesser black-backed gull",
    latin: "Larus fuscus",
    images: ["/images/fugle/maager/sildemaage_1.jpg", "/images/fugle/maager/sildemaage_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Mørkegrå ryg og gule ben — svartbagen er større med helt sort ryg og lyserøde ben.",
    features: [
      "Medium-large gull with a dark slate-grey back and yellow legs",
      "Yellow bill with a red spot near the tip",
      "Slimmer and smaller than the great black-backed gull, with a less bulky bill",
      "Many migrate south for winter, unlike the more resident herring and great black-backed gulls",
    ],
  },
  {
    id: "soelvmaage",
    category: "maager",
    name_da: "Sølvmåge",
    name_en: "European herring gull",
    latin: "Larus argentatus",
    images: ["/images/fugle/maager/soelvmaage_1.jpg", "/images/fugle/maager/soelvmaage_2.jpg"],
    weight: "800–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Lys sølvgrå ryg og lyserøde ben — sildemågen har mørkere ryg og gule ben.",
    features: [
      "Denmark's classic large gull — pale silvery-grey back, pink legs",
      "Yellow bill with a red spot on the lower mandible",
      "Common and highly adaptable, from coasts and harbours to landfill sites and rooftops",
      "Takes four years to reach full adult plumage; young birds are mottled brown",
    ],
  },
  {
    id: "stormmaage",
    category: "maager",
    name_da: "Stormmåge",
    name_en: "Common gull",
    latin: "Larus canus",
    images: ["/images/fugle/maager/stormmaage_1.jpg", "/images/fugle/maager/stormmaage_2.jpg"],
    weight: "300–500 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Ligner en lille sølvmåge, men med et tyndere, rent gult næb uden rød plet, og mørke øjne.",
    features: [
      "A smaller, daintier look-alike of the herring gull",
      "Slim, plain yellow-green bill without the herring gull's red spot",
      "Dark eyes give it a gentler expression than the larger gulls",
      "Often feeds on farmland fields well away from the coast, as well as at sea",
    ],
  },
  {
    id: "svartbag",
    category: "maager",
    name_da: "Svartbag",
    name_en: "Great black-backed gull",
    latin: "Larus marinus",
    images: ["/images/fugle/maager/svartbag_1.jpg", "/images/fugle/maager/svartbag_2.jpg"],
    weight: "1.5–2.2 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Danmarks største måge — helt sort ryg og kraftigt næb, klart større end sildemågen.",
    features: [
      "Denmark's largest gull, with a powerful bill and a heavy, bulky build",
      "Blackish-grey back, darker than any other Danish gull, with pink legs",
      "A capable predator, taking eggs, chicks, and even adult birds, alongside fish and carrion",
      "Dominates other gulls at feeding sites due to its size",
    ],
  },

  // --- Rovfugle (birds of prey) ---
  {
    id: "duehoeg",
    category: "rovfugle",
    name_da: "Duehøg",
    name_en: "Northern goshawk",
    latin: "Accipiter gentilis",
    images: [
      "/images/fugle/duer/duehoeg_1.jpg",
      "/images/fugle/rovfugle/duehoeg_1.jpg",
      "/images/fugle/rovfugle/duehoeg_2.jpg",
    ],
    weight: "600–1400 g",
    habitat: "naaleskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Kraftig, tværstribet underside og en bred hale — meget større og kraftigere end en spurvehøg, på trods af navnet ikke en due.",
    features: [
      "A large, powerful hawk — noticeably bigger and bulkier than the sparrowhawk",
      "Grey-brown above, finely barred grey-white below, with a bold white eyebrow stripe",
      "Broad wings and a long, rounded tail suited for fast, agile flight through forest",
      "Hunts birds and mammals up to the size of a pigeon or hare, often near forest edges",
    ],
  },
  {
    id: "fiskeoern",
    category: "rovfugle",
    name_da: "Fiskeørn",
    name_en: "Osprey",
    latin: "Pandion haliaetus",
    images: ["/images/fugle/rovfugle/fiskeoern_1.jpg", "/images/fugle/rovfugle/fiskeoern_2.jpg"],
    weight: "1.2–2 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Hvid underside og et tydeligt mørkt \"øjenbind\" — fanger fisk ved at dykke fødder først i vandet.",
    features: [
      "Mostly white below with a dark brown \"bandit\" stripe through the eye",
      "Dark brown above, long angled wings often held in an M-shape in flight",
      "The only Danish raptor that dives feet-first into water to catch fish",
      "A summer visitor, present from April to September",
    ],
  },
  {
    id: "kongeoern",
    category: "rovfugle",
    name_da: "Kongeørn",
    name_en: "Golden eagle",
    latin: "Aquila chrysaetos",
    images: ["/images/fugle/rovfugle/kongeoern_1.jpg", "/images/fugle/rovfugle/kongeoern_2.jpg"],
    weight: "3–6.5 kg",
    habitat: "naaleskov",
    activity: "day",
    rarity: 5,
    native: true,
    differentiator: "Enorm rovfugl med gyldne nakkefjer — langt større end musvågen, med lange, brede vinger båret i en let V-form.",
    features: [
      "One of the largest birds of prey in Europe, with a wingspan over two metres",
      "Dark brown overall with golden-tinged feathers on the back of the head and neck",
      "Soars on long, broad wings held in a shallow V — unlike the buzzard's flatter glide",
      "Extremely rare in Denmark, with only occasional sightings — not an established breeder",
    ],
  },
  {
    id: "musvaage",
    category: "rovfugle",
    name_da: "Musvåge",
    name_en: "Common buzzard",
    latin: "Buteo buteo",
    images: [
      "/images/fugle/rovfugle/musvaage_1.jpg",
      "/images/fugle/rovfugle/musvaage_2.jpg",
      "/images/fugle/rovfugle/musvaage_3.jpg",
    ],
    weight: "500–1300 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Danmarks mest almindelige rovfugl — bred, rund vingeform og kort hale, ofte siddende på vejpæle.",
    features: [
      "Denmark's most common bird of prey, often seen perched on roadside poles and fence posts",
      "Broad, rounded wings and a short, fanned tail, usually held in a shallow V while soaring",
      "Plumage varies hugely from almost white to nearly black",
      "Often mistaken for other raptors simply because it's seen so often",
    ],
  },
  {
    id: "roerhoeg",
    category: "rovfugle",
    name_da: "Rørhøg",
    name_en: "Western marsh harrier",
    latin: "Circus aeruginosus",
    images: [
      "/images/fugle/rovfugle/roerhoeg_1.jpg",
      "/images/fugle/rovfugle/roerhoeg_2.jpg",
      "/images/fugle/rovfugle/roerhoeg_3.jpg",
    ],
    weight: "400–800 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Flyver lavt over rørskove med vingerne i en tydelig V-form — kraftig, mørk krop med en lys isse hos hunnen.",
    features: [
      "Denmark's largest harrier, closely tied to reedbeds and wetlands",
      "Flies low with wings held in a distinct shallow V, tilting from side to side",
      "Females and juveniles are dark brown with a creamy crown and throat; males are more colourful with grey wing patches",
      "Nests on the ground among reeds — Denmark's most widespread breeding harrier",
    ],
  },
  {
    id: "spurvehoeg",
    category: "rovfugle",
    name_da: "Spurvehøg",
    name_en: "Eurasian sparrowhawk",
    latin: "Accipiter nisus",
    images: [
      "/images/fugle/rovfugle/spurvehoeg_1.jpg",
      "/images/fugle/rovfugle/spurvehoeg_2.jpg",
      "/images/fugle/rovfugle/spurvehoeg_3.jpg",
    ],
    weight: "150–300 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Lille, tværstribet rovfugl med korte, runde vinger og lang hale — mindre og slankere end duehøgen.",
    features: [
      "Small, agile hawk with short, rounded wings and a long tail, built for chasing birds through trees",
      "Finely barred grey-white underside, blue-grey (male) or brown (female) above",
      "Males are notably smaller than females — one of the biggest size gaps of any Danish bird",
      "A frequent visitor to gardens with bird feeders, hunting small birds",
    ],
  },
  {
    id: "vandrefalk",
    category: "rovfugle",
    name_da: "Vandrefalk",
    name_en: "Peregrine falcon",
    latin: "Falco peregrinus",
    images: [
      "/images/fugle/rovfugle/vandrefalk_1.jpg",
      "/images/fugle/rovfugle/vandrefalk_2.jpg",
      "/images/fugle/rovfugle/vandrefalk_3.jpg",
    ],
    weight: "600–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Spidse, tilbagesvejede vinger og en tydelig, mørk \"moustache\"-plet under øjet — verdens hurtigste dyr i styrtdyk.",
    features: [
      "Pointed, swept-back wings and a bold dark \"moustache\" mark below the eye",
      "Blue-grey above, finely barred white below",
      "The fastest animal on Earth in its hunting stoop, reaching over 300 km/h",
      "Once nearly wiped out by pesticides in Europe; now recovering, including on tall buildings",
    ],
  },

  // --- Skalleslugere (sawbills & cormorant) ---
  {
    id: "lilleskallesluger",
    category: "skalleslugere",
    name_da: "Lille skallesluger",
    name_en: "Smew",
    latin: "Mergellus albellus",
    images: ["/images/fugle/skalleslugere/lilleskallesluger_1.jpg", "/images/fugle/skalleslugere/lilleskallesluger_2.jpg"],
    weight: "500–800 g",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Hannen er næsten helt hvid med tynde sorte streger — den mindste og lyseste af skallesluger-slægten.",
    features: [
      "The smallest and palest of the sawbills — males look almost pure white with fine black lines",
      "Females and immatures are grey with a chestnut cap and white cheeks (\"redhead\")",
      "A serrated (\"sawbill\") bill for gripping slippery fish",
      "A winter visitor from the north and east, found on lakes and sheltered coastal waters",
    ],
  },
  {
    id: "skarv",
    category: "skalleslugere",
    name_da: "Skarv",
    name_en: "Great cormorant",
    latin: "Phalacrocorax carbo",
    images: ["/images/fugle/skalleslugere/skarv_1.jpg", "/images/fugle/skalleslugere/skarv_2.jpg"],
    weight: "2–2.5 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Stor, helsort fugl der svømmer dybt i vandet og ofte ses stå med udspredte vinger for at tørre dem.",
    features: [
      "Large, mostly black waterbird with a hook-tipped bill and a patch of bare yellow skin at the base of the bill",
      "Swims low in the water with just the head and neck showing, then dives for fish",
      "Often seen standing with wings spread out to dry, since its feathers aren't fully waterproof",
      "Breeds colonially in trees or on cliffs/islets, often in large, noisy colonies",
    ],
  },
  {
    id: "storskallesluger",
    category: "skalleslugere",
    name_da: "Stor skallesluger",
    name_en: "Goosander",
    latin: "Mergus merganser",
    images: ["/images/fugle/skalleslugere/storskallesluger_1.jpg", "/images/fugle/skalleslugere/storskallesluger_2.jpg"],
    weight: "1–1.6 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Størst af skallesluger-slægten — hannen har en glat, mørkegrøn hovedfarve uden opstående top, i modsætning til toppet skallesluger.",
    features: [
      "The largest sawbill duck, with a long, slender, serrated red bill for catching fish",
      "Males have a smooth, dark bottle-green head with no crest, a white body, and a black back",
      "Females and immatures have a chestnut head with a shaggy (not smooth) crest",
      "Found on larger lakes and rivers, diving for fish",
    ],
  },
  {
    id: "toppetskallesluger",
    category: "skalleslugere",
    name_da: "Toppet skallesluger",
    name_en: "Red-breasted merganser",
    latin: "Mergus serrator",
    images: ["/images/fugle/skalleslugere/toppetskallesluger_1.jpg", "/images/fugle/skalleslugere/toppetskallesluger_2.jpg"],
    weight: "900–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Både han og hun har en tydelig, roddet fjertop i nakken — stor skallesluger har en glat hovedform.",
    features: [
      "Both sexes have a shaggy, spiky crest on the back of the head, unlike the smooth-headed goosander",
      "Males have a dark green head, white collar, and a rusty, speckled breast band",
      "More coastal and saltwater-loving than the goosander, which prefers freshwater",
      "A fast, low flier, usually seen in small groups just above the water",
    ],
  },

  // --- Spurvefugle (crow family) ---
  {
    id: "allike",
    category: "spurvefugle",
    name_da: "Allike",
    name_en: "Western jackdaw",
    latin: "Coloeus monedula",
    images: ["/images/fugle/spurvefugle/allike_1.jpg", "/images/fugle/spurvefugle/allike_2.jpg"],
    weight: "220–270 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Mindst af kragefuglene, med et lyst, sølvgråt nakke- og kindparti og lyse, hvidgrå øjne.",
    features: [
      "Smallest of Denmark's crow family, with a pale silvery-grey nape and cheeks contrasting with a black cap",
      "Pale, whitish-grey eyes — distinctive at close range",
      "Highly social, often in noisy flocks, and frequently seen with rooks",
      "Nests in chimneys, church towers, and tree holes",
    ],
  },
  {
    id: "husskade",
    category: "spurvefugle",
    name_da: "Husskade",
    name_en: "Eurasian magpie",
    latin: "Pica pica",
    images: ["/images/fugle/spurvefugle/husskade_1.jpg", "/images/fugle/spurvefugle/husskade_2.jpg"],
    weight: "180–250 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort-hvid krage med en meget lang hale, der skinner metalgrønt-blåt i sollys — umiskendelig.",
    features: [
      "Unmistakable black-and-white plumage with a very long, iridescent green-blue tail",
      "Bold and noisy, often seen alone or in small, loose groups",
      "Builds large, domed stick nests, easy to spot in bare winter trees",
      "An opportunistic omnivore, eating everything from insects to eggs and scraps",
    ],
  },
  {
    id: "krage",
    category: "spurvefugle",
    name_da: "Krage",
    name_en: "Hooded crow",
    latin: "Corvus cornix",
    images: [
      "/images/fugle/spurvefugle/krage_1.jpg",
      "/images/fugle/spurvefugle/krage_2.jpg",
      "/images/fugle/spurvefugle/krage_3.jpg",
    ],
    weight: "400–600 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Grå krop med sort hoved, vinger og hale — råge og ravn er helt sorte over det hele.",
    features: [
      "Ash-grey body with a black head, throat, wings and tail — Denmark's only part-grey crow",
      "Stockier and less glossy than the raven, and less social than the rook",
      "Found almost everywhere: farmland, coasts, towns, and woodland edges",
      "A highly intelligent, adaptable omnivore",
    ],
  },
  {
    id: "raage",
    category: "spurvefugle",
    name_da: "Råge",
    name_en: "Rook",
    latin: "Corvus frugilegus",
    images: ["/images/fugle/spurvefugle/raage_1.jpg", "/images/fugle/spurvefugle/raage_2.jpg"],
    weight: "400–500 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Helt sort med et bart, gråhvidt næbparti hos voksne fugle — kragen har fjerklædt næb og gråt bryst.",
    features: [
      "All-black, glossy plumage, with a bare, pale greyish-white patch of skin around the base of the bill (in adults)",
      "A slightly peaked crown and shaggy \"trousers\" of feathers on the upper legs",
      "Highly social, breeding and feeding in large colonies (\"rookeries\") in farmland treetops",
      "Juveniles have a feathered face and can be confused with the hooded crow",
    ],
  },
  {
    id: "ravn",
    category: "spurvefugle",
    name_da: "Ravn",
    name_en: "Common raven",
    latin: "Corvus corax",
    images: [
      "/images/fugle/spurvefugle/ravn_1.jpg",
      "/images/fugle/spurvefugle/ravn_2.jpg",
      "/images/fugle/spurvefugle/ravn_3.jpg",
    ],
    weight: "800–1500 g",
    habitat: "naaleskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Danmarks største spurvefugl — helt sort med et meget kraftigt næb og en kileformet hale.",
    features: [
      "Denmark's largest songbird, all black with a heavy, powerful bill",
      "Long, wedge-shaped tail, visible in flight — square-ended in the similarly-sized crow",
      "Deep, croaking \"gronk\" call, quite different from a crow's harsher caw",
      "Was once persecuted to near-extinction in Denmark but has recovered strongly",
    ],
  },
  {
    id: "skovskade",
    category: "spurvefugle",
    name_da: "Skovskade",
    name_en: "Eurasian jay",
    latin: "Garrulus glandarius",
    images: ["/images/fugle/spurvefugle/skovskade_1.jpg", "/images/fugle/spurvefugle/skovskade_2.jpg"],
    weight: "140–190 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Rødbrun krage med en tydelig, lyseblå vingeplet — ingen anden dansk fugl har den kombination.",
    features: [
      "Pinkish-brown body with a striking patch of bright blue, black-barred feathers on the wing",
      "Black moustache stripe and a white rump, conspicuous in flight",
      "Shy woodland bird, but its harsh, screeching call carries far",
      "Buries acorns for winter, and inadvertently helps spread oak trees",
    ],
  },

  // --- Storke (storks & herons) ---
  {
    id: "fiskehejre",
    category: "storke",
    name_da: "Fiskehejre",
    name_en: "Grey heron",
    latin: "Ardea cinerea",
    images: ["/images/fugle/storke/fiskehejre_1.jpg", "/images/fugle/storke/fiskehejre_2.jpg"],
    weight: "1–2 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Står musestille og lurer ved vandkanten med bøjet hals — langt større end nogen af vadefuglene.",
    features: [
      "Tall, grey-and-white wading bird with a long neck, often held in an S-curve",
      "Stands motionless for long periods, waiting to spike fish with its dagger-like bill",
      "Black stripe over the eye extending into wispy plumes at the back of the head",
      "Flies with slow wingbeats and the neck tucked in — unlike storks, which fly with necks extended",
    ],
  },
  {
    id: "stork",
    category: "storke",
    name_da: "Stork",
    name_en: "White stork",
    latin: "Ciconia ciconia",
    images: ["/images/fugle/storke/stork_1.jpg", "/images/fugle/storke/stork_2.jpg"],
    weight: "2.3–4.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 5,
    native: true,
    differentiator: "Hvid krop med sorte vingefjer og et langt, rødt næb — flyver med udstrakt hals, i modsætning til fiskehejren.",
    features: [
      "Large white bird with black flight feathers and a long, straight red bill and legs",
      "Flies with the neck fully extended, unlike the heron's tucked-in neck",
      "Once bred across Denmark but nearly disappeared; now the subject of active reintroduction projects",
      "Famous for large stick nests built on rooftops and poles in its European range",
    ],
  },

  // --- Svaner (swans) ---
  {
    id: "knopsvane",
    category: "svaner",
    name_da: "Knopsvane",
    name_en: "Mute swan",
    latin: "Cygnus olor",
    images: ["/images/fugle/svaner/knopsvane_1.jpg", "/images/fugle/svaner/knopsvane_2.jpg"],
    weight: "8–12 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Orange næb med en sort basisknop — sangsvanen har et gult og sort næb uden knop.",
    features: [
      "Denmark's national bird — orange bill with a black knob at the base",
      "Holds its neck in a graceful S-curve, often with wings raised in a threat display",
      "Denmark's most common and widespread swan, on lakes, rivers, and coastal waters",
      "Largely silent, though it hisses when threatened — hence \"mute\" swan",
    ],
  },
  {
    id: "sangsvane",
    category: "svaner",
    name_da: "Sangsvane",
    name_en: "Whooper swan",
    latin: "Cygnus cygnus",
    images: ["/images/fugle/svaner/sangsvane_1.jpg", "/images/fugle/svaner/sangsvane_2.jpg"],
    weight: "8–11 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Gult og sort næb i en kileform, uden knop — holder halsen lige i stedet for en S-kurve.",
    features: [
      "Yellow-and-black bill in a wedge shape, with no knob — the clearest difference from the mute swan",
      "Holds its neck straight, not curved into an S-shape",
      "A loud, trumpeting call, often given by flocks in flight",
      "A winter visitor from the north, with a small and growing number of breeding pairs",
    ],
  },
  {
    id: "sortsvane",
    category: "svaner",
    name_da: "Sortsvane",
    name_en: "Black swan",
    latin: "Cygnus atratus",
    images: ["/images/fugle/svaner/sortsvane_1.jpg"],
    weight: "3.7–6.7 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Helt sort fjerdragt med et rødt næb — findes kun som undslupne parkfugle i Danmark, ikke som vild bestand.",
    features: [
      "Entirely black plumage with a bright red bill",
      "Native to Australia — only present in Denmark as escapees from parks and private collections",
      "Curly, ornate wing feathers visible when the wings are raised",
      "Not an established wild breeding species in Denmark",
    ],
  },

  // --- Svømmeænder (dabbling ducks) ---
  {
    id: "atlingand",
    category: "svoemmeaender",
    name_da: "Atlingand",
    name_en: "Garganey",
    latin: "Spatula querquedula",
    images: ["/images/fugle/svoemmeaender/atlingand_1.jpg", "/images/fugle/svoemmeaender/atlingand_2.jpg"],
    weight: "300–400 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Hannen har et bredt, hvidt øjenbryn, der buer bagud over et mørkerødbrunt hoved — Danmarks eneste rene sommertrækkende and.",
    features: [
      "Males have a broad white eyebrow stripe curving back over a dark chestnut-brown head",
      "Denmark's only duck that is a pure summer visitor, absent in winter",
      "Females are mottled brown and easily confused with a female teal",
      "Found on shallow, vegetated wetlands and flooded meadows",
    ],
  },
  {
    id: "graaand",
    category: "svoemmeaender",
    name_da: "Gråand",
    name_en: "Mallard",
    latin: "Anas platyrhynchos",
    images: [
      "/images/fugle/svoemmeaender/graaand_1.jpg",
      "/images/fugle/svoemmeaender/graaand_2.jpg",
      "/images/fugle/svoemmeaender/graaand_3.jpg",
    ],
    weight: "900–1300 g",
    habitat: "soeer",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Danmarks mest almindelige and — hannen har et glinsende grønt hoved og en hvid halsring.",
    features: [
      "Denmark's most common and familiar duck — the ancestor of most domestic ducks",
      "Males have a glossy green head, white neck ring, and a yellow bill",
      "Females are mottled brown with an orange-and-black bill",
      "Found on almost any body of water, from ponds and lakes to city parks",
    ],
  },
  {
    id: "gravand",
    category: "svoemmeaender",
    name_da: "Gravand",
    name_en: "Common shelduck",
    latin: "Tadorna tadorna",
    images: ["/images/fugle/svoemmeaender/gravand_1.jpg", "/images/fugle/svoemmeaender/gravand_2.jpg"],
    weight: "900–1500 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Stor, goose-lignende and med et rødt næb og en bred, kastanjebrun brystring på ellers hvid krop.",
    features: [
      "Large, goose-like duck, mostly white with a broad chestnut breast band and a glossy dark green head",
      "Bright red bill, more prominent in males with a knob at the base",
      "Common on mudflats and sandy coasts, especially the Wadden Sea",
      "Nests in burrows, often old rabbit holes, unlike most ducks",
    ],
  },
  {
    id: "knarand",
    category: "svoemmeaender",
    name_da: "Knarand",
    name_en: "Gadwall",
    latin: "Mareca strepera",
    images: ["/images/fugle/svoemmeaender/knarand_1.jpg", "/images/fugle/svoemmeaender/knarand_2.jpg"],
    weight: "600–1000 g",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hannen ser gråbrun og kedelig ud på afstand, men har en sort bag — kig efter det hvide vingespejl i flugt.",
    features: [
      "Males look plain grey-brown at a distance, but show a black rear end up close",
      "A white patch on the inner wing (speculum), visible in flight or at rest",
      "Females closely resemble female mallards but are slimmer with a thinner, orange-sided bill",
      "Found on lakes and marshes, often in smaller numbers than mallard",
    ],
  },
  {
    id: "krikand",
    category: "svoemmeaender",
    name_da: "Krikand",
    name_en: "Eurasian teal",
    latin: "Anas crecca",
    images: ["/images/fugle/svoemmeaender/krikand_1.jpg", "/images/fugle/svoemmeaender/krikand_2.jpg"],
    weight: "250–400 g",
    habitat: "vaadomrader",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Danmarks mindste svømmeand — hannen har et rødbrunt hoved med et bredt, grønt bånd om øjet.",
    features: [
      "Denmark's smallest dabbling duck, fast-flying and agile",
      "Males have a chestnut head with a broad green band curving back through the eye",
      "Females are mottled brown, best told from other small ducks by their size and fast, twisting flight",
      "Found on shallow wetlands, flooded fields, and ditches",
    ],
  },
  {
    id: "pibeand",
    category: "svoemmeaender",
    name_da: "Pibeand",
    name_en: "Eurasian wigeon",
    latin: "Mareca penelope",
    images: ["/images/fugle/svoemmeaender/pibeand_1.jpg", "/images/fugle/svoemmeaender/pibeand_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Hannen har en rustrød isse med en cremegul pandeplet — kendes også på den karakteristiske, fløjtende \"piiuu\"-lyd.",
    features: [
      "Males have a chestnut head with a creamy-yellow forehead stripe, and a mostly grey body",
      "Named for its distinctive whistled \"wheeoo\" call, often heard before the bird is seen",
      "Grazes on grass and aquatic vegetation, sometimes in large flocks on coastal grassland",
      "Mainly a winter visitor to Denmark from further north",
    ],
  },
  {
    id: "skeand",
    category: "svoemmeaender",
    name_da: "Skeand",
    name_en: "Northern shoveler",
    latin: "Spatula clypeata",
    images: ["/images/fugle/svoemmeaender/skeand_1.jpg", "/images/fugle/svoemmeaender/skeand_2.jpg"],
    weight: "500–1000 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Det store, skeformede næb er umiskendeligt — intet andet dansk and har den næbform.",
    features: [
      "Unmistakable large, spoon-shaped bill, used to filter tiny food particles from the water surface",
      "Males have a dark green head, white breast, and chestnut flanks",
      "Often swims with its head low and bill skimming the water surface",
      "Found on shallow, muddy wetlands and flooded fields",
    ],
  },
  {
    id: "spidsand",
    category: "svoemmeaender",
    name_da: "Spidsand",
    name_en: "Northern pintail",
    latin: "Anas acuta",
    images: [
      "/images/fugle/svoemmeaender/spidsand_1.jpg",
      "/images/fugle/svoemmeaender/spidsand_2.jpg",
      "/images/fugle/svoemmeaender/spidsand_3.jpg",
    ],
    weight: "600–1400 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Slank and med en lang, spids hale og en tynd, hvid stribe op ad den chokoladebrune hals.",
    features: [
      "Elegant, slender duck with a long, pointed tail (most obvious in males)",
      "Males have a chocolate-brown head with a thin white stripe running up the side of the neck",
      "Long neck gives it a distinctive, elongated silhouette compared to other dabbling ducks",
      "Mainly seen in Denmark on passage and in winter",
    ],
  },

  // --- Vadefugle (waders) ---
  {
    id: "brushane",
    category: "vadefugle",
    name_da: "Brushane",
    name_en: "Ruff",
    latin: "Calidris pugnax",
    images: ["/images/fugle/vadefugle/brushane_1.jpg", "/images/fugle/vadefugle/brushane_2.jpg"],
    weight: "70–250 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Meget varierende fjerdragt og størrelse — hannen kan i yngledragt have en stor, farverig fjerkrave, unik blandt danske vadefugle.",
    features: [
      "Highly variable plumage and size between individuals — unusual among waders",
      "Breeding males can grow an extravagant, colourful neck ruff and head tufts for display",
      "Females (\"reeves\") are much smaller and plainer than males",
      "Found on wet meadows and mudflats, mainly on migration in Denmark",
    ],
  },
  {
    id: "dobbeltbekkasin",
    category: "vadefugle",
    name_da: "Dobbeltbekkasin",
    name_en: "Common snipe",
    latin: "Gallinago gallinago",
    images: [
      "/images/fugle/vadefugle/dobbeltbekkasin_1.jpg",
      "/images/fugle/vadefugle/dobbeltbekkasin_2.jpg",
      "/images/fugle/vadefugle/dobbeltbekkasin_3.jpg",
    ],
    weight: "80–140 g",
    habitat: "vaadomrader",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Meget langt, lige næb og stribet ryg i kraftig kontrast — mindre og slankere end skovsneppen, som lever i skov, ikke mose.",
    features: [
      "Very long, straight bill relative to its body size, used to probe deep into mud for invertebrates",
      "Strongly striped back, with cryptic brown camouflage",
      "Explosive, zigzagging escape flight when flushed",
      "Found in wet meadows, bogs, and marshes — unlike the woodland-dwelling woodcock",
    ],
  },
  {
    id: "enkeltbekkasin",
    category: "vadefugle",
    name_da: "Enkeltbekkasin",
    name_en: "Jack snipe",
    latin: "Lymnocryptes minimus",
    images: ["/images/fugle/vadefugle/enkeltbekkasin_1.jpg", "/images/fugle/vadefugle/enkeltbekkasin_2.jpg"],
    weight: "35–70 g",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Mindre end dobbeltbekkasin med et kortere næb, og flyver stille og lavt op i stedet for i skarpe zigzag.",
    features: [
      "Smaller than the common snipe, with a proportionally shorter bill",
      "Flushes silently and flies low and direct, without the common snipe's sharp zigzagging",
      "Extremely well camouflaged and reluctant to fly, often flushing only at the last moment",
      "A scarce passage and winter visitor, easily overlooked",
    ],
  },
  {
    id: "hjejle",
    category: "vadefugle",
    name_da: "Hjejle",
    name_en: "European golden plover",
    latin: "Pluvialis apricaria",
    images: ["/images/fugle/vadefugle/hjejle_1.jpg", "/images/fugle/vadefugle/hjejle_2.jpg"],
    weight: "150–250 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Guldgullige-brune, spraglede overside og en rund, lille hovedform — danner ofte store, tætte flokke i luften.",
    features: [
      "Golden-brown, speckled upperparts give the species its name",
      "Rounded head and short bill, typical of the plover family",
      "Forms large, tightly packed flocks that wheel and turn together in flight",
      "Found on farmland, coastal grassland, and mudflats, mainly outside the breeding season in Denmark",
    ],
  },
  {
    id: "hvidklirre",
    category: "vadefugle",
    name_da: "Hvidklire",
    name_en: "Common greenshank",
    latin: "Tringa nebularia",
    images: ["/images/fugle/vadefugle/hvidklirre_1.jpg", "/images/fugle/vadefugle/hvidklirre_2.jpg"],
    weight: "150–270 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Langt, let opadbøjet næb og grønlige ben — en hvid overgump ses tydeligt i flugt, i kontrast til den mørkere ryg.",
    features: [
      "Long, slightly upturned bill and long, greenish-yellow legs",
      "A pale, whitish rump visible in flight, contrasting with darker back and wings",
      "Loud, ringing three-note call, often heard before the bird is seen",
      "Passes through Denmark on migration between Arctic breeding grounds and African/southern winter grounds",
    ],
  },
  {
    id: "islandskryle",
    category: "vadefugle",
    name_da: "Islandsk ryle",
    name_en: "Purple sandpiper",
    latin: "Calidris maritima",
    images: ["/images/fugle/vadefugle/islandskryle_1.jpg", "/images/fugle/vadefugle/islandsryle_2.jpg"],
    weight: "60–100 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Mørk, næsten sortgrå vader med gule ben, der altid ses på sten og moler langs kysten — sjældent på blød mudderflade.",
    features: [
      "Dark, slate-grey wader with a slightly downcurved bill with a yellow base",
      "Yellow-orange legs, standing out against its dark plumage",
      "Almost always found on rocky shores, breakwaters, and jetties, rather than soft mud",
      "A hardy winter visitor from Arctic breeding grounds",
    ],
  },
  {
    id: "lillekobbersneppe",
    category: "vadefugle",
    name_da: "Lille kobbersneppe",
    name_en: "Bar-tailed godwit",
    latin: "Limosa lapponica",
    images: ["/images/fugle/vadefugle/lillekobbersneppe_1.jpg", "/images/fugle/vadefugle/lillekobbersneppe_2.jpg"],
    weight: "190–400 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Let opadbøjet næb og en stribet (ikke ensfarvet) hale — stor kobbersneppe har et lige næb og en bred, sort halebånd.",
    features: [
      "Long, slightly upturned bill",
      "Barred tail pattern, unlike the black-tailed godwit's bold black-and-white tail",
      "No white wing bar in flight, unlike the black-tailed godwit",
      "A key migratory stopover species in the Wadden Sea",
    ],
  },
  {
    id: "lilleregnspove",
    category: "vadefugle",
    name_da: "Lille regnspove",
    name_en: "Whimbrel",
    latin: "Numenius phaeopus",
    images: [
      "/images/fugle/vadefugle/lilleregnspove_1.jpg",
      "/images/fugle/vadefugle/lilleregnspove_2.jpg",
      "/images/fugle/vadefugle/lilleregnspove_3.jpg",
    ],
    weight: "270–450 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Kortere næb med et tydeligt knæk nær spidsen, og et stribet isseparti — stor regnspove har et jævnt, ensartet krumt næb.",
    features: [
      "Shorter bill than the curlew, with a distinct kink near the tip rather than one smooth curve",
      "Bold dark crown stripes bordering a pale central crown stripe — the curlew lacks this pattern",
      "Passes through Denmark on migration between Arctic breeding grounds and African wintering areas",
      "A classic confusion species with the larger curlew",
    ],
  },
  {
    id: "roedben",
    category: "vadefugle",
    name_da: "Rødben",
    name_en: "Common redshank",
    latin: "Tringa totanus",
    images: ["/images/fugle/vadefugle/roedben_1.jpg", "/images/fugle/vadefugle/roedben_2.jpg"],
    weight: "85–155 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Klart orange-røde ben og en næbbasis i samme farve — et hvidt bagkantsbånd på vingerne er tydeligt i flugt.",
    features: [
      "Bright orange-red legs and a matching red base to the bill — hence the name",
      "Bold white trailing edge on the wings, conspicuous in flight",
      "Noisy and alert, often the first bird to raise the alarm on wetlands",
      "Breeds on salt marshes and wet meadows along the coast",
    ],
  },
  {
    id: "skovsneppe",
    category: "vadefugle",
    name_da: "Skovsneppe",
    name_en: "Eurasian woodcock",
    latin: "Scolopax rusticola",
    images: [
      "/images/fugle/vadefugle/skovsneppe_1.jpg",
      "/images/fugle/vadefugle/skovsneppe_2.jpg",
      "/images/fugle/vadefugle/skovsneppe_3.jpg",
    ],
    weight: "240–420 g",
    habitat: "loevskov",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Lever i skov (ikke mose) med en tværstribet, ikke længdestribet, isse — store øjne placeret højt og langt tilbage på hovedet.",
    features: [
      "A woodland wader — unusual among snipes and godwits, which favour open wetlands",
      "Barred (not striped) crown pattern, and large eyes set high and far back on the head for near all-round vision",
      "Mottled brown, superbly camouflaged among leaf litter",
      "Performs a distinctive slow, croaking display flight (\"roding\") over the forest at dusk in spring",
    ],
  },
  {
    id: "sortklirre",
    category: "vadefugle",
    name_da: "Sortklire",
    name_en: "Spotted redshank",
    latin: "Tringa erythropus",
    images: ["/images/fugle/vadefugle/sortklirre_2.jpg"],
    weight: "97–160 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "I sommerdragt næsten helt sort — om vinteren en meget lysere, gråere fugl med et længere, tyndere næb end rødben.",
    features: [
      "In breeding plumage, almost entirely sooty-black — unique among Danish waders",
      "In winter, much paler grey above and white below, similar to redshank but with a longer, finer bill",
      "Legs are dark red, duller than the redshank's bright orange-red",
      "Passes through Denmark on migration, mainly in spring and autumn",
    ],
  },
  {
    id: "storkobbersneppe",
    category: "vadefugle",
    name_da: "Stor kobbersneppe",
    name_en: "Black-tailed godwit",
    latin: "Limosa limosa",
    images: [
      "/images/fugle/vadefugle/storkobbersneppe_1.jpg",
      "/images/fugle/vadefugle/storkobbersneppe_2.jpg",
      "/images/fugle/vadefugle/storkobbersneppe_3.jpg",
    ],
    weight: "280–500 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Langt, lige næb og en bred, sort halebånd med et tydeligt hvidt vingebånd i flugt — lille kobbersneppe har opadbøjet næb.",
    features: [
      "Long, straight bill (unlike the bar-tailed godwit's upturned bill)",
      "Bold white wing bar and a broad black band across the tail, striking in flight",
      "One of Denmark's rarest breeding waders, nesting in wet meadows",
      "Long legs trail well beyond the tail in flight",
    ],
  },
  {
    id: "storregnspove",
    category: "vadefugle",
    name_da: "Stor regnspove",
    name_en: "Eurasian curlew",
    latin: "Numenius arquata",
    images: [
      "/images/fugle/vadefugle/storregnspove_1.jpg",
      "/images/fugle/vadefugle/storregnspove_2.jpg",
      "/images/fugle/vadefugle/storregnspove_3.jpg",
    ],
    weight: "575–1000 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Danmarks største vadefugl, med et meget langt næb, der bøjer jævnt hele vejen — ingen tydelig isseplet som lille regnspove.",
    features: [
      "Denmark's largest wader, with a very long, evenly downcurved bill",
      "Plain, unstriped crown — unlike the whimbrel's bold dark-and-pale crown stripes",
      "A haunting, bubbling call, often given in flight over mudflats",
      "The Wadden Sea holds internationally important numbers on migration and in winter",
    ],
  },
  {
    id: "strandskade",
    category: "vadefugle",
    name_da: "Strandskade",
    name_en: "Eurasian oystercatcher",
    latin: "Haematopus ostralegus",
    images: ["/images/fugle/vadefugle/strandskade_1.jpg", "/images/fugle/vadefugle/strandskade_2.jpg"],
    weight: "400–700 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort-hvid med et langt, kraftigt, knaldorange næb — umiskendelig blandt danske vadefugle.",
    features: [
      "Bold black-and-white plumage with a long, thick, bright orange-red bill",
      "Pink legs and a red eye-ring",
      "Uses its strong bill to pry open or hammer through shellfish, especially mussels and cockles",
      "Loud, piping calls, often given in noisy display flights",
    ],
  },
  {
    id: "vibe",
    category: "vadefugle",
    name_da: "Vibe",
    name_en: "Northern lapwing",
    latin: "Vanellus vanellus",
    images: ["/images/fugle/vadefugle/vibe_1.jpg", "/images/fugle/vadefugle/vibe_2.jpg"],
    weight: "150–300 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Lang, tynd fjertop og iriserende grøn-sort overside — brede, runde vinger giver en karakteristisk \"flappende\" flugt.",
    features: [
      "Long, thin head crest and iridescent green-black upperparts that can look almost purple in the light",
      "Broad, rounded wings give a distinctive, floppy flight style",
      "One of the first waders to return to Danish farmland in early spring",
      "Performs tumbling, acrobatic display flights over breeding territory",
    ],
  },

  // --- Vandhøns (rails & coots) ---
  {
    id: "blishoene",
    category: "vandhoens",
    name_da: "Blishøne",
    name_en: "Eurasian coot",
    latin: "Fulica atra",
    images: ["/images/fugle/vandhoens/blishoene.jpg", "/images/fugle/vandhoens/blishoene_2.jpg"],
    weight: "600–900 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Helsort krop med en hvid, skjoldformet pandeplet og næb — grønbenet rørhøne har rødt næb med gul spids.",
    features: [
      "All-black body with a white, shield-shaped frontal shield and bill",
      "Bright red eyes",
      "Aggressive and territorial, often seen chasing other coots and ducks on the water",
      "Dives frequently for water plants, unlike the more surface-feeding moorhen",
    ],
  },
  {
    id: "groenbenetroerhoene",
    category: "vandhoens",
    name_da: "Grønbenet rørhøne",
    name_en: "Common moorhen",
    latin: "Gallinula chloropus",
    images: ["/images/fugle/vandhoens/groenbenetroerhoene_1.jpg", "/images/fugle/vandhoens/groenbenetroerhoene_2.jpg"],
    weight: "250–400 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Rødt næb med gul spids og en hvid stribe langs siden — blishønen har et helt hvidt næb/pandeplet.",
    features: [
      "Red bill with a yellow tip, and a red frontal shield",
      "A white stripe along the flanks and white patches under the tail, flicked while swimming",
      "Long, greenish-yellow legs and long toes for walking on floating vegetation",
      "More secretive than the coot, often staying closer to reeds and bankside cover",
    ],
  },
];

export default SPECIES;
