// All birds used in the quiz, grouped by category (see
// birdCategories.js). Mirrors species.js's schema exactly — see that
// file for what each field means (images, weight, habitat, activity,
// rarity, native, differentiator, confusedWith, features).
//
// Kendetegn, forveksling and (where given) weights are taken from the
// "Vildt & Jagt" handbook (Fugle). Species the book doesn't cover
// (knopsvane, sangsvane, stork, kongeørn) keep their earlier data, and
// islandskryle is left as-is because its photos show a purple sandpiper.
//
// A couple of species have photos spread across two folders on disk
// (e.g. huldue lives partly under fugle/duer and partly under
// fugle/spurvefugle) — that's just where the files landed, not a
// taxonomic split, so their `images` arrays pull from both paths.

const SPECIES = [
  // --- Duer (pigeons & doves) ---
  {
    id: "huldue",
    category: "duer",
    name_da: "Huldue",
    name_en: "Stock dove",
    latin: "Columba oenas",
    images: [
      "/images/fugle/duer/huldue_1.jpg",
      "/images/fugle/spurvefugle/huldue_2.jpg",
      "/images/fugle/spurvefugle/huldue_3.jpg",
    ],
    weight: "260–330 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Ensfarvet blå due med to sorte striber på hver vinge og mørkt øje — ringduen har hvide vingefelter og et hvidt-grønt halsbånd.",
    confusedWith: ["ringdue"],
    features: [
      "Two short black bars on each wing",
      "Uniformly blue-grey dove with a dark eye and dark wingtips",
      "No white neck patch and no white in the wing — unlike the woodpigeon",
      "Nests in tree holes and old buildings, and is often overlooked among flocks of woodpigeons",
    ],
  },
  {
    id: "ringdue",
    category: "duer",
    name_da: "Ringdue",
    name_en: "Common woodpigeon",
    latin: "Columba palumbus",
    images: ["/images/fugle/duer/ringdue_1.jpg", "/images/fugle/duer/ringdue_2.jpg", "/images/fugle/duer/ringdue_3.jpg"],
    weight: "480–550 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Hvidt felt på overvingen (tydeligt i flugt) og et grønt-hvidt halsbånd midt på halsen — hulduen har sorte vingestriber og intet hvidt.",
    confusedWith: ["huldue"],
    features: [
      "White patch on the upper wing, clearly visible in flight",
      "Green and white neck band reaching forward to the middle of the neck (missing on juveniles)",
      "Denmark's largest and most common dove, plump and grey with a pinkish breast",
      "Often seen in large flocks on fields and in parks",
    ],
  },
  {
    id: "tyrkerdue",
    category: "duer",
    name_da: "Tyrkerdue",
    name_en: "Eurasian collared dove",
    latin: "Streptopelia decaocto",
    images: ["/images/fugle/duer/tyrkerdue_1.jpg", "/images/fugle/duer/tyrkerdue_2.jpg"],
    weight: "150–220 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Sort, halvcirkelformet nakkebånd på en lysegrå krop — væsentligt mindre og slankere end de øvrige duer.",
    confusedWith: [],
    features: [
      "Black half-circle band on the back of the neck",
      "Pale grey plumage with dark wingtips",
      "Noticeably smaller and slimmer than the other Danish pigeons",
      "Strongly tied to towns, gardens and farms",
    ],
  },

  // --- Dykænder (diving ducks) ---
  {
    id: "amerikanskskarveand",
    category: "dykaender",
    name_da: "Amerikansk skarveand",
    name_en: "Ruddy duck",
    latin: "Oxyura jamaicensis",
    images: ["/images/fugle/dykaender/amerikanskskarveand_1.jpg", "/images/fugle/dykaender/amerikanskskarveand_2.jpg"],
    weight: "300–800 g",
    habitat: "soeer",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Lille and med hvid kind og mørk isse — hannen har kastaniebrun krop og lyseblåt næb; kan næppe forveksles med andre.",
    confusedWith: [],
    features: [
      "Male: chestnut-brown neck and body, black/dark-brown crown, nape and tail, and a pale blue bill",
      "Male: bright white cheeks",
      "Female: mottled brown with a dark-brown crown, a whitish cheek and a brown bill",
      "A small, stiff-tailed duck — invasive in Denmark",
    ],
  },
  {
    id: "bjergand",
    category: "dykaender",
    name_da: "Bjergand",
    name_en: "Greater scaup",
    latin: "Aythya marila",
    images: ["/images/fugle/dykaender/bjergand_1.jpg", "/images/fugle/dykaender/bjergand_2.jpg"],
    weight: "800–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hannen har grå ryg og ingen top — troldandens han har sort ryg og hængende top; hunnen har et lyst felt ved næbroden.",
    confusedWith: ["troldand"],
    features: [
      "Male: black head, neck and breast, grey back and white belly",
      "Female: blackish-brown with a pale patch at the base of the bill",
      "Both sexes have a bluish bill with a dark tip",
      "No crest — the easiest way to tell it from the tufted duck",
    ],
  },
  {
    id: "ederfugl",
    category: "dykaender",
    name_da: "Ederfugl",
    name_en: "Common eider",
    latin: "Somateria mollissima",
    images: [
      "/images/fugle/dykaender/ederfugl_1.jpg",
      "/images/fugle/dykaender/ederfugl_2.jpg",
      "/images/fugle/dykaender/ederfugl_3.jpg",
    ],
    weight: "1.2–2.8 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Væsentligt større end de øvrige dykænder — hannen er sort-hvid med grøn nakke, hunnen ensfarvet varmbrun.",
    confusedWith: [],
    features: [
      "Adult male: black and white with a green nape",
      "Young males are patchy black and white",
      "Female: warm, uniform brown — juveniles look like the female",
      "Much larger than the other diving ducks",
    ],
  },
  {
    id: "floejlsand",
    category: "dykaender",
    name_da: "Fløjlsand",
    name_en: "Velvet scoter",
    latin: "Melanitta fusca",
    images: ["/images/fugle/dykaender/floejlsand_1.jpg", "/images/fugle/dykaender/floejlsand_2.jpg"],
    weight: "1.2–2 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Sort eller mørkebrun and med et tydeligt hvidt vingespejl — sortanden har intet hvidt i vingen.",
    confusedWith: ["sortand"],
    features: [
      "Male: black with a clear white wing patch (speculum) and a yellow bill",
      "Female: dark brown with a white speculum, a dark bill and a small white spot behind the eye",
      "Juveniles look like the female",
      "The white wing patch separates it from the common scoter",
    ],
  },
  {
    id: "havlit",
    category: "dykaender",
    name_da: "Havlit",
    name_en: "Long-tailed duck",
    latin: "Clangula hyemalis",
    images: ["/images/fugle/dykaender/havlit_1.jpg", "/images/fugle/dykaender/havlit_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hannen har meget lange, forlængede midterste halefjer og et sort næb med rosa bånd — en udpræget havdykker langt fra land.",
    confusedWith: [],
    features: [
      "Male: very long central tail feathers",
      "Male: black bill with a striking pink band, and a pinkish cheek",
      "Female: mottled grey-brown with a dark back, pale belly and pale patches on the head",
      "A true sea duck, often seen far from land",
    ],
  },
  {
    id: "hvinand",
    category: "dykaender",
    name_da: "Hvinand",
    name_en: "Common goldeneye",
    latin: "Bucephala clangula",
    images: ["/images/fugle/dykaender/hvinand_1.jpg", "/images/fugle/dykaender/hvinand_2.jpg"],
    weight: "700–1200 g",
    habitat: "soeer",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Hannen har en stor, rund hvid plet ved næbroden og gule øjne; vingerne giver en karakteristisk hvinende lyd i flugt.",
    confusedWith: ["taffeland"],
    features: [
      "Male: black head with a large round white spot at the base of the bill, and yellow eyes",
      "Female: mottled grey-brown body and back, with a brown head",
      "Both sexes have a tall, somewhat flattened head shape",
      "The wings make a distinctive whistling/ringing sound in flight",
    ],
  },
  {
    id: "roedhovedetand",
    category: "dykaender",
    name_da: "Rødhovedet and",
    name_en: "Red-crested pochard",
    latin: "Netta rufina",
    images: [
      "/images/fugle/dykaender/roedhovedetand_1.jpg",
      "/images/fugle/dykaender/roedhovedetand_2.jpg",
      "/images/fugle/dykaender/roedhovedetand_3.jpg",
    ],
    weight: "900–1300 g",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: false,
    differentiator: "Smalt og højt næb (orange hos hannen) — taffelanden har et bredt næb med sort spids, og hannen er grå på ryggen.",
    confusedWith: ["taffeland"],
    features: [
      "Male: upper neck and head bright red-orange",
      "Female: paler brown breast and belly, darker brown back, pale cheeks and a brown cap above the eyes",
      "Both sexes have a fairly narrow, high bill — dark with a pale tip on the female, orange on the male",
      "Easily confused with the pochard of the same sex",
    ],
  },
  {
    id: "sortand",
    category: "dykaender",
    name_da: "Sortand",
    name_en: "Common scoter",
    latin: "Melanitta nigra",
    images: ["/images/fugle/dykaender/sortand_1.jpg", "/images/fugle/dykaender/sortand_2.jpg"],
    weight: "800–1500 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Hannen er helt sort med et rødgult felt på næbbet — uden det hvide vingespejl, som fløjlsanden har.",
    confusedWith: ["floejlsand"],
    features: [
      "Male: completely black, with a reddish-yellow patch on the bill",
      "Female: dark brown body with a dark-brown cap and paler grey-brown throat and neck",
      "Juveniles are more mottled",
      "No white in the wing — unlike the velvet scoter",
    ],
  },
  {
    id: "taffeland",
    category: "dykaender",
    name_da: "Taffeland",
    name_en: "Common pochard",
    latin: "Aythya ferina",
    images: ["/images/fugle/dykaender/taffeland_1.jpg", "/images/fugle/dykaender/taffeland_2.jpg"],
    weight: "700–1100 g",
    habitat: "soeer",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Bredt, blåt næb med sort spids — rødhovedet and har et smalt og højt næb; hannen har rødbrunt hoved og sort bryst.",
    confusedWith: ["roedhovedetand", "hvinand"],
    features: [
      "Male: red-brown head, black breast, grey body and red eyes",
      "Male: broad blue bill with a black tip, and a grey speculum",
      "Female: brown head and neck with a paler area between bill and eye, and a grey-brown body",
      "Female: dark, broad bill with a black tip",
    ],
  },
  {
    id: "troldand",
    category: "dykaender",
    name_da: "Troldand",
    name_en: "Tufted duck",
    latin: "Aythya fuligula",
    images: [
      "/images/fugle/dykaender/troldand_1.jpg",
      "/images/fugle/dykaender/troldand_2.jpg",
      "/images/fugle/dykaender/troldand_3.jpg",
    ],
    weight: "600–1000 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Tydelig hængende top og sort ryg hos hannen — bjergandens han har grå ryg og ingen top.",
    confusedWith: ["bjergand"],
    features: [
      "Male: black head and back with a clear black crest",
      "Female: black/dark-brown head and back, paler brown breast and belly, and a smaller crest",
      "Both sexes have a white speculum",
      "Both sexes have a bluish bill with a dark tip",
    ],
  },

  // --- Fasanfugle (gamebirds) ---
  {
    id: "agerhoene",
    category: "fasanfugle",
    name_da: "Agerhøne",
    name_en: "Grey partridge",
    latin: "Perdix perdix",
    images: ["/images/fugle/fasanfugle/agerhoene_1.jpg", "/images/fugle/fasanfugle/agerhoene_2.jpg"],
    weight: "300–400 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Lille, buttet, gråbrun hønsefugl med et mørkebrunt brystskjold — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Small, plump, grey-brown gamebird",
      "Dark-brown horseshoe patch on the breast",
      "Lives in coveys (flocks) on farmland",
      "Cannot be confused with any other species",
    ],
  },
  {
    id: "fasan",
    category: "fasanfugle",
    name_da: "Fasan",
    name_en: "Common pheasant",
    latin: "Phasianus colchicus",
    images: [
      "/images/fugle/fasanfugle/fasan_1.jpg",
      "/images/fugle/fasanfugle/fasan_2.jpg",
      "/images/fugle/fasanfugle/fasan_3.jpg",
    ],
    weight: "0.9–1.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Kokken er meget farverig med lange halefjer og ofte en hvid halsring; hønen er lysebrun med sorte pletter og kortere hale.",
    confusedWith: [],
    features: [
      "Cock: very colourful with long tail feathers — typically red, blue and green metallic colours, and many have a clear white neck ring",
      "Hen: normally light brown speckled with black, but colour variants occur, including almost uniformly dark birds",
      "The cock has long spurs; the hen has small, stubby spurs",
      "Cannot be confused with any other species",
    ],
  },

  // --- Gæs (geese) ---
  {
    id: "blisgaas",
    category: "gaes",
    name_da: "Blisgås",
    name_en: "Greater white-fronted goose",
    latin: "Anser albifrons",
    images: ["/images/fugle/gaes/blisgaas_1.jpg", "/images/fugle/gaes/blisgaas_2.jpg"],
    weight: "2–3.2 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hvid blis i panden og sorte tværstriber på bryst og bug hos de voksne, samt orange-gule ben.",
    confusedWith: ["graagaas", "kortnaebbetgaas", "saedgaas"],
    features: [
      "Adults have a white blaze on the forehead",
      "Adults have dark (black) bars on the breast and belly",
      "Orange-yellow legs",
      "Occurs in large flocks",
    ],
  },
  {
    id: "bramgaas",
    category: "gaes",
    name_da: "Bramgås",
    name_en: "Barnacle goose",
    latin: "Branta leucopsis",
    images: ["/images/fugle/gaes/bramgaas_1.jpg", "/images/fugle/gaes/bramgaas_2.jpg"],
    weight: "1.3–2.2 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Lille gås med hvid kind — canadagåsen er dobbelt så stor, og stemmen er et godt kendetegn.",
    confusedWith: ["canadagaas", "kortnaebbetgaas"],
    features: [
      "Small goose with white cheeks",
      "Dark grey upper side and a pale belly",
      "Seen in large, very noisy flocks",
      "Can be confused with the short-billed goose in poor light — the voice is a good clue",
    ],
  },
  {
    id: "canadagaas",
    category: "gaes",
    name_da: "Canadagås",
    name_en: "Canada goose",
    latin: "Branta canadensis",
    images: [
      "/images/fugle/gaes/canadagaas_1.jpg",
      "/images/fugle/gaes/canadagaas_2.jpg",
      "/images/fugle/gaes/canadagaas_3.jpg",
    ],
    weight: "3.5–6.5 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: false,
    differentiator: "Den største gås — sort hoved og hals med en hvid strubeplet, der går op bag øjnene.",
    confusedWith: ["bramgaas"],
    features: [
      "Black head and neck",
      "White throat patch reaching up behind the eyes",
      "Dark upper side and pale belly",
      "The largest of the geese — the barnacle goose is less than half its size and sounds very different",
    ],
  },
  {
    id: "graagaas",
    category: "gaes",
    name_da: "Grågås",
    name_en: "Greylag goose",
    latin: "Anser anser",
    images: ["/images/fugle/gaes/graagaas_1.jpg", "/images/fugle/gaes/graagaas_2.jpg", "/images/fugle/gaes/graagaas_3.jpg"],
    weight: "3–3.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Lysegrå forvinge, der er tydelig i flugt, og kødfarvet næb og ben — de mørkere sædgås og kortnæbbet gås har sort næb med lyst bånd.",
    confusedWith: ["kortnaebbetgaas", "saedgaas", "blisgaas"],
    features: [
      "Pale grey forewing, clearly visible in flight",
      "Flesh-coloured (pink) legs and bill",
      "Grey to grey-brown plumage",
      "Flies in V-formation; the second-largest goose and both a breeding bird and migrant in Denmark",
    ],
  },
  {
    id: "knortegaas",
    category: "gaes",
    name_da: "Knortegås",
    name_en: "Brant goose",
    latin: "Branta bernicla",
    images: ["/images/fugle/gaes/knortegaas_1.jpg", "/images/fugle/gaes/knortegaas_2.jpg"],
    weight: "1.3–1.6 kg",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Lille, mørk gås med sort hoved og hals, en hvid halsplet og en lysende hvid undergump — flyver ikke i kileformation.",
    confusedWith: ["bramgaas"],
    features: [
      "Head, bill and neck black, with distinct white patches on the neck (missing on juveniles)",
      "Dark upper side",
      "White under-tail, very visible on the water",
      "A small goose that doesn't fly in V-formation — coastal, feeding on eelgrass",
    ],
  },
  {
    id: "kortnaebbetgaas",
    category: "gaes",
    name_da: "Kortnæbbet gås",
    name_en: "Pink-footed goose",
    latin: "Anser brachyrhynchus",
    images: ["/images/fugle/gaes/kortnaebbetgaas_1.jpg", "/images/fugle/gaes/kortnaebbetgaas_2.jpg"],
    weight: "2–3 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Lille, mørkebrunt hoved og sort næb med kødfarvet bånd — lysere forvinge og lidt mindre end sædgåsen, som den ellers ligner næsten fuldstændigt.",
    confusedWith: ["saedgaas", "graagaas"],
    features: [
      "Small, dark-brown head",
      "Black bill with a flesh-coloured band near the tip",
      "Darker than the greylag goose",
      "A very common migrant in western Jutland — doesn't breed in Denmark",
    ],
  },
  {
    id: "nilgaas",
    category: "gaes",
    name_da: "Nilgås",
    name_en: "Egyptian goose",
    latin: "Alopochen aegyptiaca",
    images: ["/images/fugle/gaes/nilgaas_1.jpg", "/images/fugle/gaes/nilgaas_2.jpg"],
    weight: "1.5–2.3 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: false,
    differentiator: "Broget fjerdragt med et hvidligt hoved og en tydelig mørkebrun plet om øjet — lange blegrøde ben.",
    confusedWith: ["gravand"],
    features: [
      "Mottled plumage with a whitish head and a clear dark-brown patch around the eye",
      "Upper side in shades of reddish-brown and grey-brown",
      "Long, pale-pink legs",
      "Pale belly with a dark spot — invasive in Denmark",
    ],
  },
  {
    id: "saedgaas",
    category: "gaes",
    name_da: "Sædgås",
    name_en: "Taiga bean goose",
    latin: "Anser fabalis",
    images: ["/images/fugle/gaes/saedgaas_1.jpg", "/images/fugle/gaes/saedgaas_2.jpg"],
    weight: "2.5–3.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Mørkebrunt hoved, orangegule ben og sort næb med kødfarvet bånd — kortnæbbet gås har lysere forvinge og findes mest på vestkysten.",
    confusedWith: ["kortnaebbetgaas", "graagaas"],
    features: [
      "Dark-brown head",
      "Orange-yellow legs",
      "Black bill with a flesh-coloured band near the tip",
      "Darker plumage than the greylag goose; flies in V-formation, mainly in eastern Denmark",
    ],
  },

  // --- Måger (gulls) ---
  {
    id: "haettemaage",
    category: "maager",
    name_da: "Hættemåge",
    name_en: "Black-headed gull",
    latin: "Chroicocephalus ridibundus",
    images: ["/images/fugle/maager/haettemaage_1.jpg", "/images/fugle/maager/haettemaage_2.jpg"],
    weight: "200–400 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort bagkant og hvid forkant på vingen, og mørkebrun hætte om sommeren — om vinteren kun en mørk plet bag øjet.",
    confusedWith: ["stormmaage"],
    features: [
      "Black trailing edge and white leading edge on the wing",
      "Striking dark-brown hood in summer plumage",
      "Dark spot behind the eye in winter plumage",
      "Only confused with the common gull in winter, when it has lost its hood",
    ],
  },
  {
    id: "sildemaage",
    category: "maager",
    name_da: "Sildemåge",
    name_en: "Lesser black-backed gull",
    latin: "Larus fuscus",
    images: ["/images/fugle/maager/sildemaage_1.jpg", "/images/fugle/maager/sildemaage_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Sortblå ryg og gule ben — sølvmågen har blågrå ryg og kødfarvede ben, og svartbagen er væsentligt større.",
    confusedWith: ["soelvmaage", "svartbag"],
    features: [
      "Blackish-blue upper side",
      "Strong bill with an orange spot near the tip of the lower mandible",
      "Yellow legs",
      "Juveniles are mottled brown",
    ],
  },
  {
    id: "soelvmaage",
    category: "maager",
    name_da: "Sølvmåge",
    name_en: "European herring gull",
    latin: "Larus argentatus",
    images: ["/images/fugle/maager/soelvmaage_1.jpg", "/images/fugle/maager/soelvmaage_2.jpg"],
    weight: "800–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Blågrå ryg og kødfarvede ben — sildemågen har sortblå ryg og gule ben, og stormmågen er væsentligt mindre.",
    confusedWith: ["sildemaage", "stormmaage"],
    features: [
      "Blue-grey upper side",
      "Strong bill with a red spot on the underside near the tip",
      "Flesh-coloured legs",
      "A large gull — juveniles are mottled brown; protected since 2014",
    ],
  },
  {
    id: "stormmaage",
    category: "maager",
    name_da: "Stormmåge",
    name_en: "Common gull",
    latin: "Larus canus",
    images: ["/images/fugle/maager/stormmaage_1.jpg", "/images/fugle/maager/stormmaage_2.jpg"],
    weight: "300–500 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Grå ryg og sorte vingespidser, ellers hvid — meget mindre end sølvmågen og uden hættemågens sommerhætte.",
    confusedWith: ["soelvmaage", "haettemaage"],
    features: [
      "Black wingtips",
      "Grey upper side, otherwise white",
      "Juveniles are mottled brown",
      "Much smaller than the herring gull",
    ],
  },
  {
    id: "svartbag",
    category: "maager",
    name_da: "Svartbag",
    name_en: "Great black-backed gull",
    latin: "Larus marinus",
    images: ["/images/fugle/maager/svartbag_1.jpg", "/images/fugle/maager/svartbag_2.jpg"],
    weight: "1.5–2.2 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Danmarks største måge med sortblå ryg og grålig kødfarvede ben — sildemågen ligner, men er mindre og har gule ben.",
    confusedWith: ["sildemaage"],
    features: [
      "Blackish-blue upper side",
      "Strong yellow bill with a red spot near the tip of the lower mandible",
      "In flight shows 2–3 white spots in the wingtip",
      "Greyish flesh-coloured legs — juveniles are mottled brown",
    ],
  },

  // --- Rovfugle (birds of prey) ---
  {
    id: "duehoeg",
    category: "rovfugle",
    name_da: "Duehøg",
    name_en: "Northern goshawk",
    latin: "Accipiter gentilis",
    images: [
      "/images/fugle/duer/duehoeg_1.jpg",
      "/images/fugle/rovfugle/duehoeg_1.jpg",
      "/images/fugle/rovfugle/duehoeg_2.jpg",
    ],
    weight: "600–1400 g",
    habitat: "naaleskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Større, kraftigere og dybere i brystet end spurvehøgen — hunnen er på størrelse med en musvåge.",
    confusedWith: ["spurvehoeg"],
    features: [
      "Blue-grey upper side and barred breast and belly (white with dark bars)",
      "Long, narrow tail and short, broad, rounded wings",
      "Big size difference between the sexes — the female is largest, about the size of a buzzard",
      "A male goshawk and a female sparrowhawk can be very hard to tell apart",
    ],
  },
  {
    id: "fiskeoern",
    category: "rovfugle",
    name_da: "Fiskeørn",
    name_en: "Osprey",
    latin: "Pandion haliaetus",
    images: ["/images/fugle/rovfugle/fiskeoern_1.jpg", "/images/fugle/rovfugle/fiskeoern_2.jpg"],
    weight: "1.2–2 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Lange vinger med tydeligt albueknæk, lys underside og et mørkt bånd fra nakken frem til næbbet.",
    confusedWith: ["soelvmaage", "svartbag"],
    features: [
      "Long wings with a distinct bend at the wrist",
      "Pale underside, pale nape and crown, and pale throat",
      "Dark band from the nape running along the side of the head to the bill",
      "Dark upper side — at a distance in flight its silhouette can resemble a large gull",
    ],
  },
  {
    id: "kongeoern",
    category: "rovfugle",
    name_da: "Kongeørn",
    name_en: "Golden eagle",
    latin: "Aquila chrysaetos",
    images: ["/images/fugle/rovfugle/kongeoern_1.jpg", "/images/fugle/rovfugle/kongeoern_2.jpg"],
    weight: "3–6.5 kg",
    habitat: "naaleskov",
    activity: "day",
    rarity: 5,
    native: true,
    differentiator: "Enorm rovfugl med gyldne nakkefjer — langt større end musvågen, med lange, brede vinger båret i en let V-form.",
    confusedWith: [],
    features: [
      "One of the largest birds of prey in Europe, with a wingspan over two metres",
      "Dark brown overall with golden-tinged feathers on the back of the head and neck",
      "Soars on long, broad wings held in a shallow V — unlike the buzzard's flatter glide",
      "Extremely rare in Denmark, with only occasional sightings — not an established breeder",
    ],
  },
  {
    id: "musvaage",
    category: "rovfugle",
    name_da: "Musvåge",
    name_en: "Common buzzard",
    latin: "Buteo buteo",
    images: [
      "/images/fugle/rovfugle/musvaage_1.jpg",
      "/images/fugle/rovfugle/musvaage_2.jpg",
      "/images/fugle/rovfugle/musvaage_3.jpg",
    ],
    weight: "500–1300 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Kraftig, bredskuldret rovfugl — normalt brun, men med mange farvevarianter fra næsten hvid til helt mørk.",
    confusedWith: ["roerhoeg"],
    features: [
      "Powerful, broad-shouldered bird of prey",
      "Brown, but very variable — from almost white to completely dark",
      "Often seen sitting on posts and in trees along roads and fields",
      "In flight it can especially be confused with honey buzzard and rough-legged buzzard",
    ],
  },
  {
    id: "roerhoeg",
    category: "rovfugle",
    name_da: "Rørhøg",
    name_en: "Western marsh harrier",
    latin: "Circus aeruginosus",
    images: [
      "/images/fugle/rovfugle/roerhoeg_1.jpg",
      "/images/fugle/rovfugle/roerhoeg_2.jpg",
      "/images/fugle/rovfugle/roerhoeg_3.jpg",
    ],
    weight: "400–800 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Holder vingerne i et tydeligt V over ryggen under svæveflugt — hannen er trefarvet gråblå, brun og sort.",
    confusedWith: ["musvaage"],
    features: [
      "Male: three-coloured — blue-grey, brown and black",
      "Female and juveniles: brown with a pale yellowish crown",
      "Holds its wings in a V above the back when gliding",
      "At a distance it can resemble a buzzard or other harriers",
    ],
  },
  {
    id: "spurvehoeg",
    category: "rovfugle",
    name_da: "Spurvehøg",
    name_en: "Eurasian sparrowhawk",
    latin: "Accipiter nisus",
    images: [
      "/images/fugle/rovfugle/spurvehoeg_1.jpg",
      "/images/fugle/rovfugle/spurvehoeg_2.jpg",
      "/images/fugle/rovfugle/spurvehoeg_3.jpg",
    ],
    weight: "150–300 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Mindre og spinklere end duehøgen — især spurvehøgens hun og duehøgens han kan være svære at skelne.",
    confusedWith: ["duehoeg"],
    features: [
      "Blue-grey upper side and barred breast and belly (white with dark bars)",
      "Long, narrow tail and short, rounded wings",
      "Big size difference between the sexes — the female is largest",
      "A specialist small-bird hunter, often seen taking birds up to blackbird size at garden feeders",
    ],
  },
  {
    id: "vandrefalk",
    category: "rovfugle",
    name_da: "Vandrefalk",
    name_en: "Peregrine falcon",
    latin: "Falco peregrinus",
    images: [
      "/images/fugle/rovfugle/vandrefalk_1.jpg",
      "/images/fugle/rovfugle/vandrefalk_2.jpg",
      "/images/fugle/rovfugle/vandrefalk_3.jpg",
    ],
    weight: "600–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Kompakt, bredskuldret storfalk med lange, smalle vinger og en tydelig sort hætte.",
    confusedWith: [],
    features: [
      "Long, narrow wings",
      "Black hood (moustache)",
      "Compact, broad-shouldered large falcon",
      "Dark-grey upper side and pale underside with dark bars — the female is clearly larger than the male",
    ],
  },

  // --- Skalleslugere (sawbills & cormorant) ---
  {
    id: "lilleskallesluger",
    category: "skalleslugere",
    name_da: "Lille skallesluger",
    name_en: "Smew",
    latin: "Mergellus albellus",
    images: ["/images/fugle/skalleslugere/lilleskallesluger_1.jpg", "/images/fugle/skalleslugere/lilleskallesluger_2.jpg"],
    weight: "500–800 g",
    habitat: "soeer",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Hannen er kridhvid med sorte aftegninger og hvid top — hunnen er grå med en lille top på en rødbrun isse.",
    confusedWith: ["toppetskallesluger", "storskallesluger"],
    features: [
      "Male: chalk-white with black markings on the head and body",
      "Male: white crest",
      "Female: greyer, with a small crest on a red-brown crown",
      "Only the female can be confused with other species",
    ],
  },
  {
    id: "skarv",
    category: "skalleslugere",
    name_da: "Skarv",
    name_en: "Great cormorant",
    latin: "Phalacrocorax carbo",
    images: ["/images/fugle/skalleslugere/skarv_1.jpg", "/images/fugle/skalleslugere/skarv_2.jpg"],
    weight: "2–2.5 kg",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort, gåsestor fugl med lang hals og et langt, smalt krognæb — i flugt skifter den mellem baskning og glideflugt, modsat gæssene.",
    confusedWith: [],
    features: [
      "Black, goose-sized bird with a long neck",
      "Strong, long, narrow bill with a hooked tip, and white markings at the base of the bill",
      "Breeding males have white thigh patches; juveniles have a grey-brown breast and belly",
      "Often seen drying its wings on posts and stones — nests in colonies in trees or on the ground",
    ],
  },
  {
    id: "storskallesluger",
    category: "skalleslugere",
    name_da: "Stor skallesluger",
    name_en: "Goosander",
    latin: "Mergus merganser",
    images: ["/images/fugle/skalleslugere/storskallesluger_1.jpg", "/images/fugle/skalleslugere/storskallesluger_2.jpg"],
    weight: "1–1.6 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hannen er langstrakt sort-hvid med sort hoved uden synlig top — toppet skallesluger har tydelig top hos begge køn.",
    confusedWith: ["toppetskallesluger"],
    features: [
      "Male: large white patch on the upper wing plus a white speculum",
      "Male: long black-and-white bird with a black head (no visible crest), a long, red, pointed bill, red legs, and a pinkish sheen on the white belly",
      "Female: white speculum, grey-and-brown body and a chestnut head with a crest",
      "Both species of large sawbill have a white speculum",
    ],
  },
  {
    id: "toppetskallesluger",
    category: "skalleslugere",
    name_da: "Toppet skallesluger",
    name_en: "Red-breasted merganser",
    latin: "Mergus serrator",
    images: ["/images/fugle/skalleslugere/toppetskallesluger_1.jpg", "/images/fugle/skalleslugere/toppetskallesluger_2.jpg"],
    weight: "900–1300 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Tydelig top hos begge køn — hannen har hvid halsring og brunt brystbånd; hunnen mangler den skarpe kontrast mellem hals og krop.",
    confusedWith: ["storskallesluger"],
    features: [
      "Male: black head with a crest, a white neck ring and a brown breast band",
      "Male: large white patch on the upper wing plus a white speculum",
      "Female: grey-brown upper side without a sharp contrast to the brown/grey neck",
      "Female: brown head with a crest",
    ],
  },

  // --- Spurvefugle (crow family) ---
  {
    id: "allike",
    category: "spurvefugle",
    name_da: "Allike",
    name_en: "Western jackdaw",
    latin: "Coloeus monedula",
    images: ["/images/fugle/spurvefugle/allike_1.jpg", "/images/fugle/spurvefugle/allike_2.jpg"],
    weight: "220–270 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort med grå nakke og hals og et hvidgult øje — betydeligt mindre end de øvrige kragefugle.",
    confusedWith: [],
    features: [
      "Black, with a grey nape and neck",
      "Whitish-yellow eye",
      "Nests in chimneys, ventilation shafts, church towers and hollow trees",
      "Often found close to human settlement",
    ],
  },
  {
    id: "husskade",
    category: "spurvefugle",
    name_da: "Husskade",
    name_en: "Eurasian magpie",
    latin: "Pica pica",
    images: ["/images/fugle/spurvefugle/husskade_1.jpg", "/images/fugle/spurvefugle/husskade_2.jpg"],
    weight: "180–250 g",
    habitat: "beboelse",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Lang, sort hale og sort-hvid fjerdragt med hvid bug og hvidt på vingerne — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Long black tail",
      "Black and white: black head and back, white belly and white on the wings",
      "Builds a round, domed nest in trees in gardens, parks, hedgerows and copses",
      "Omnivorous — takes grain, worms and rubbish as well as eggs and young of small birds",
    ],
  },
  {
    id: "krage",
    category: "spurvefugle",
    name_da: "Krage",
    name_en: "Hooded crow",
    latin: "Corvus cornix",
    images: [
      "/images/fugle/spurvefugle/krage_1.jpg",
      "/images/fugle/spurvefugle/krage_2.jpg",
      "/images/fugle/spurvefugle/krage_3.jpg",
    ],
    weight: "400–600 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Gråkragen har sort hoved og bryst og grå ryg og bug; den helt sorte sortkrage kendes fra råge på, at den mangler det bare hudfelt ved næbroden.",
    confusedWith: ["raage", "ravn"],
    features: [
      "Comes in two forms: hooded crow and carrion crow",
      "Hooded crow: black head, throat and breast",
      "Hooded crow: grey back and belly",
      "Carrion crow: all black — mostly found in Southern Jutland",
    ],
  },
  {
    id: "raage",
    category: "spurvefugle",
    name_da: "Råge",
    name_en: "Rook",
    latin: "Corvus frugilegus",
    images: ["/images/fugle/spurvefugle/raage_1.jpg", "/images/fugle/spurvefugle/raage_2.jpg"],
    weight: "400–500 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Voksne har et tydeligt, bart hudparti ved næbroden — det er sådan, rågen kendes fra sortkragen.",
    confusedWith: ["krage", "ravn"],
    features: [
      "Black — adults with a metallic gloss, juveniles more matt black",
      "Adults have a clear, bare patch of skin at the base of the bill",
      "Breeds in colonies large and small, increasingly in town parks",
      "Mainly eats grain, but also many earthworms and crane-fly larvae",
    ],
  },
  {
    id: "ravn",
    category: "spurvefugle",
    name_da: "Ravn",
    name_en: "Common raven",
    latin: "Corvus corax",
    images: [
      "/images/fugle/spurvefugle/ravn_1.jpg",
      "/images/fugle/spurvefugle/ravn_2.jpg",
      "/images/fugle/spurvefugle/ravn_3.jpg",
    ],
    weight: "800–1500 g",
    habitat: "naaleskov",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Helt sort med kraftigt sort næb og kileformet hale i flugt — væsentligt større end sortkrage og råge.",
    confusedWith: ["krage", "raage"],
    features: [
      "All black",
      "Powerful black bill",
      "Wedge-shaped tail, visible in flight",
      "Much larger than the carrion crow and rook",
    ],
  },
  {
    id: "skovskade",
    category: "spurvefugle",
    name_da: "Skovskade",
    name_en: "Eurasian jay",
    latin: "Garrulus glandarius",
    images: ["/images/fugle/spurvefugle/skovskade_1.jpg", "/images/fugle/spurvefugle/skovskade_2.jpg"],
    weight: "140–190 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Farvestrålende lyseblå fjer på vingen, en lille top og et hvidt parti ved halen i flugt — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Brilliant pale-blue feathers on the wing",
      "Elongated crown feathers form a small crest",
      "White rump patch at the base of the tail, visible in flight",
      "Cannot be confused with any other species",
    ],
  },

  // --- Storke (storks & herons) ---
  {
    id: "fiskehejre",
    category: "storke",
    name_da: "Fiskehejre",
    name_en: "Grey heron",
    latin: "Ardea cinerea",
    images: ["/images/fugle/storke/fiskehejre_1.jpg", "/images/fugle/storke/fiskehejre_2.jpg"],
    weight: "1–2 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Lange ben, lang hals og langt næb — i flugt trækker den halsen ind i et S og strækker benene bagud.",
    confusedWith: [],
    features: [
      "Long bill, long neck and long legs",
      "Grey upper side, pale underside with black lengthwise streaks",
      "Clear crest on the head (not visible in flight)",
      "In flight the neck is pulled in and the legs stretch out behind",
    ],
  },
  {
    id: "stork",
    category: "storke",
    name_da: "Stork",
    name_en: "White stork",
    latin: "Ciconia ciconia",
    images: ["/images/fugle/storke/stork_1.jpg", "/images/fugle/storke/stork_2.jpg"],
    weight: "2.3–4.5 kg",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 5,
    native: true,
    differentiator: "Hvid krop med sorte vingefjer og et langt, rødt næb — flyver med udstrakt hals, i modsætning til fiskehejren.",
    confusedWith: ["fiskehejre"],
    features: [
      "Large white bird with black flight feathers and a long, straight red bill and legs",
      "Flies with the neck fully extended, unlike the heron's tucked-in neck",
      "Once bred across Denmark but nearly disappeared; now the subject of active reintroduction projects",
      "Famous for large stick nests built on rooftops and poles in its European range",
    ],
  },

  // --- Svaner (swans) ---
  {
    id: "knopsvane",
    category: "svaner",
    name_da: "Knopsvane",
    name_en: "Mute swan",
    latin: "Cygnus olor",
    images: ["/images/fugle/svaner/knopsvane_1.jpg", "/images/fugle/svaner/knopsvane_2.jpg"],
    weight: "8–12 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Orange næb med en sort basisknop — sangsvanen har et gult og sort næb uden knop.",
    confusedWith: ["sangsvane"],
    features: [
      "Denmark's national bird — orange bill with a black knob at the base",
      "Holds its neck in a graceful S-curve, often with wings raised in a threat display",
      "Denmark's most common and widespread swan, on lakes, rivers, and coastal waters",
      "Largely silent, though it hisses when threatened — hence \"mute\" swan",
    ],
  },
  {
    id: "sangsvane",
    category: "svaner",
    name_da: "Sangsvane",
    name_en: "Whooper swan",
    latin: "Cygnus cygnus",
    images: ["/images/fugle/svaner/sangsvane_1.jpg", "/images/fugle/svaner/sangsvane_2.jpg"],
    weight: "8–11 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Gult og sort næb i en kileform, uden knop — holder halsen lige i stedet for en S-kurve.",
    confusedWith: ["knopsvane"],
    features: [
      "Yellow-and-black bill in a wedge shape, with no knob — the clearest difference from the mute swan",
      "Holds its neck straight, not curved into an S-shape",
      "A loud, trumpeting call, often given by flocks in flight",
      "A winter visitor from the north, with a small and growing number of breeding pairs",
    ],
  },
  {
    id: "sortsvane",
    category: "svaner",
    name_da: "Sortsvane",
    name_en: "Black swan",
    latin: "Cygnus atratus",
    images: ["/images/fugle/svaner/sortsvane_1.jpg"],
    weight: "3.7–6.7 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Den eneste sorte svane — rødt næb med et hvidt tværbånd yderst.",
    confusedWith: [],
    features: [
      "Black plumage",
      "Red bill with a white band near the tip",
      "Invasive, but may not be hunted or culled",
      "Cannot be confused with any other species",
    ],
  },

  // --- Svømmeænder (dabbling ducks) ---
  {
    id: "atlingand",
    category: "svoemmeaender",
    name_da: "Atlingand",
    name_en: "Garganey",
    latin: "Spatula querquedula",
    images: ["/images/fugle/svoemmeaender/atlingand_1.jpg", "/images/fugle/svoemmeaender/atlingand_2.jpg"],
    weight: "300–400 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Hannen har et hvidt bånd fra foran øjet bagud ned ad nakken og gråblå forvinge — hunnen ligner meget krikandens hun.",
    confusedWith: ["krikand"],
    features: [
      "Dull-green speculum framed by white bars",
      "Male: white stripe from in front of the eye back and down the nape",
      "Male: brown-mottled breast, pale grey-mottled belly and blue-grey forewing",
      "Female: warm brown with dark elongated spots",
    ],
  },
  {
    id: "graaand",
    category: "svoemmeaender",
    name_da: "Gråand",
    name_en: "Mallard",
    latin: "Anas platyrhynchos",
    images: [
      "/images/fugle/svoemmeaender/graaand_1.jpg",
      "/images/fugle/svoemmeaender/graaand_2.jpg",
      "/images/fugle/svoemmeaender/graaand_3.jpg",
    ],
    weight: "1300–1500 g",
    habitat: "soeer",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Blåt vingespejl med et hvidt bånd på begge sider — knarandens spejl er hvidt, spidsandens brunligt.",
    confusedWith: ["knarand", "spidsand"],
    features: [
      "Blue speculum; in flight a white band shows on both sides of it",
      "Male: green head with a white neck ring",
      "Female: warm brown with dark elongated spots — only she is easily confused",
      "Denmark's most common duck and the ancestor of domestic ducks",
    ],
  },
  {
    id: "gravand",
    category: "svoemmeaender",
    name_da: "Gravand",
    name_en: "Common shelduck",
    latin: "Tadorna tadorna",
    images: ["/images/fugle/svoemmeaender/gravand_1.jpg", "/images/fugle/svoemmeaender/gravand_2.jpg"],
    weight: "900–1500 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Spraglet i tre farver — hvid, sort og rødbrun — med et rødbrunt bælte om kroppen og rødt næb.",
    confusedWith: ["nilgaas"],
    features: [
      "Three-coloured: white, black and red-brown",
      "Red-brown belt around the body",
      "Red bill",
      "The male has a red knob on the bill in breeding plumage",
    ],
  },
  {
    id: "knarand",
    category: "svoemmeaender",
    name_da: "Knarand",
    name_en: "Gadwall",
    latin: "Mareca strepera",
    images: ["/images/fugle/svoemmeaender/knarand_1.jpg", "/images/fugle/svoemmeaender/knarand_2.jpg"],
    weight: "600–1000 g",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Hvidt vingespejl hos begge køn — gråanden har blåt spejl; hannen har sort undergump.",
    confusedWith: ["graaand"],
    features: [
      "White speculum in both sexes",
      "Male: black under-tail, grey body and black bill",
      "Female: warm brown with dark elongated spots and a yellow bill",
      "The female closely resembles a female mallard — check the speculum",
    ],
  },
  {
    id: "krikand",
    category: "svoemmeaender",
    name_da: "Krikand",
    name_en: "Eurasian teal",
    latin: "Anas crecca",
    images: ["/images/fugle/svoemmeaender/krikand_1.jpg", "/images/fugle/svoemmeaender/krikand_2.jpg"],
    weight: "220–400 g",
    habitat: "vaadomrader",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Hannen har et bredt grønt bånd fra øjet bagud og en gullig undergump — Danmarks mindste svømmeand.",
    confusedWith: ["atlingand"],
    features: [
      "Green speculum",
      "Male: broad green band from in front of the eye back down the nape",
      "Male: grey-mottled body and yellowish under-tail",
      "Female: warm brown, looking plumper than other female dabbling ducks",
    ],
  },
  {
    id: "pibeand",
    category: "svoemmeaender",
    name_da: "Pibeand",
    name_en: "Eurasian wigeon",
    latin: "Mareca penelope",
    images: ["/images/fugle/svoemmeaender/pibeand_1.jpg", "/images/fugle/svoemmeaender/pibeand_2.jpg"],
    weight: "600–900 g",
    habitat: "kystvand",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Hannen har et stort hvidt felt på overvingen og et brunt hoved med gullig pandeblis.",
    confusedWith: ["graaand", "knarand"],
    features: [
      "Male: clear white patch on the upper wing (not the speculum)",
      "Male: brown head with a yellowish forehead blaze",
      "Female: reddish-brown with a slightly darker upper side",
      "Males and juveniles have a white underside and a blue bill; seen in large flocks",
    ],
  },
  {
    id: "skeand",
    category: "svoemmeaender",
    name_da: "Skeand",
    name_en: "Northern shoveler",
    latin: "Spatula clypeata",
    images: ["/images/fugle/svoemmeaender/skeand_1.jpg", "/images/fugle/svoemmeaender/skeand_2.jpg"],
    weight: "500–1000 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Det brede, skeformede næb hos begge køn er umiskendeligt.",
    confusedWith: [],
    features: [
      "Green speculum with a white bar above it",
      "Both sexes have a broad, spoon-shaped bill",
      "Male: dark-green head, blue patch on the forewing, brown belly and white breast",
      "Female: warm brownish with larger areas of black",
    ],
  },
  {
    id: "spidsand",
    category: "svoemmeaender",
    name_da: "Spidsand",
    name_en: "Northern pintail",
    latin: "Anas acuta",
    images: [
      "/images/fugle/svoemmeaender/spidsand_1.jpg",
      "/images/fugle/svoemmeaender/spidsand_2.jpg",
      "/images/fugle/svoemmeaender/spidsand_3.jpg",
    ],
    weight: "600–1400 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Slankere end gråanden med længere og smallere hals — hannen har lange, spidse halefjer og hvidt bånd op ad halsen.",
    confusedWith: ["graaand"],
    features: [
      "Greenish-brown speculum",
      "Male: elongated central tail feathers",
      "Male: chestnut head with a white breast and neck stripe reaching up the back of the neck, and a grey-mottled body",
      "Female: warm brown and speckled; both sexes are slimmer than mallards, with a longer, thinner neck",
    ],
  },

  // --- Vadefugle (waders) ---
  {
    id: "brushane",
    category: "vadefugle",
    name_da: "Brushane",
    name_en: "Ruff",
    latin: "Calidris pugnax",
    images: ["/images/fugle/vadefugle/brushane_1.jpg", "/images/fugle/vadefugle/brushane_2.jpg"],
    weight: "70–250 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Lille hoved på en relativt lang hals og lange gullige ben — hannen har en markant halskrave i yngledragt.",
    confusedWith: ["roedben"],
    features: [
      "Small head on a relatively long neck",
      "Short to medium-length dark bill; scapulars clearly edged pale",
      "Long yellowish legs",
      "Breeding males have a striking ruff in many colours; in winter both sexes look alike and greyish",
    ],
  },
  {
    id: "dobbeltbekkasin",
    category: "vadefugle",
    name_da: "Dobbeltbekkasin",
    name_en: "Common snipe",
    latin: "Gallinago gallinago",
    images: [
      "/images/fugle/vadefugle/dobbeltbekkasin_1.jpg",
      "/images/fugle/vadefugle/dobbeltbekkasin_2.jpg",
      "/images/fugle/vadefugle/dobbeltbekkasin_3.jpg",
    ],
    weight: "80–140 g",
    habitat: "vaadomrader",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Langt, lige næb og lyse og mørke længdestriber på hovedet — enkeltbekkasinen ligner, men er væsentligt mindre med kortere næb.",
    confusedWith: ["enkeltbekkasin"],
    features: [
      "Long, straight bill",
      "Pale and dark stripes running lengthwise along the head",
      "Flies off in a zig-zag with a hoarse call when flushed",
      "Usually alone or in small groups on soft, wet meadows and along ditches",
    ],
  },
  {
    id: "enkeltbekkasin",
    category: "vadefugle",
    name_da: "Enkeltbekkasin",
    name_en: "Jack snipe",
    latin: "Lymnocryptes minimus",
    images: ["/images/fugle/vadefugle/enkeltbekkasin_1.jpg", "/images/fugle/vadefugle/enkeltbekkasin_2.jpg"],
    weight: "35–70 g",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Ligner dobbeltbekkasinen, men er væsentligt mindre og har et kortere, halvlangt næb.",
    confusedWith: ["dobbeltbekkasin"],
    features: [
      "Medium-length, straight bill",
      "Pale and dark stripes running lengthwise along the head",
      "Much smaller than the common snipe",
      "Easily confused with the common snipe — size and bill length are the best clues",
    ],
  },
  {
    id: "hjejle",
    category: "vadefugle",
    name_da: "Hjejle",
    name_en: "European golden plover",
    latin: "Pluvialis apricaria",
    images: ["/images/fugle/vadefugle/hjejle_1.jpg", "/images/fugle/vadefugle/hjejle_2.jpg"],
    weight: "150–250 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Gul- og sortspættet overside helt frem til det korte næb — strandhjejlen har sort-hvid overside og sorte armhulefjer.",
    confusedWith: [],
    features: [
      "Gold-and-black spangled upper side all the way to the short bill",
      "Black belly, breast and underside of the head and neck in summer — gone in winter plumage",
      "Medium-sized wader seen in large flocks",
      "Very rare as a breeding bird, but a common migrant on farmland and sand flats",
    ],
  },
  {
    id: "hvidklirre",
    category: "vadefugle",
    name_da: "Hvidklire",
    name_en: "Common greenshank",
    latin: "Tringa nebularia",
    images: ["/images/fugle/vadefugle/hvidklirre_1.jpg", "/images/fugle/vadefugle/hvidklirre_2.jpg"],
    weight: "150–270 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Grønne ben og let opadbøjet, langt næb — rødben har røde ben og sortklire i vinterdragt røde ben.",
    confusedWith: ["roedben", "sortklirre"],
    features: [
      "Green legs",
      "Grey upper side and white underside",
      "Long, slightly upturned bill",
      "Can be confused with redshank and winter-plumaged spotted redshank",
    ],
  },
  {
    id: "islandskryle",
    category: "vadefugle",
    name_da: "Islandsk ryle",
    name_en: "Purple sandpiper",
    latin: "Calidris maritima",
    images: ["/images/fugle/vadefugle/islandskryle_1.jpg", "/images/fugle/vadefugle/islandsryle_2.jpg"],
    weight: "60–100 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Mørk, næsten sortgrå vader med gule ben, der altid ses på sten og moler langs kysten — sjældent på blød mudderflade.",
    confusedWith: [],
    features: [
      "Dark, slate-grey wader with a slightly downcurved bill with a yellow base",
      "Yellow-orange legs, standing out against its dark plumage",
      "Almost always found on rocky shores, breakwaters, and jetties, rather than soft mud",
      "A hardy winter visitor from Arctic breeding grounds",
    ],
  },
  {
    id: "lillekobbersneppe",
    category: "vadefugle",
    name_da: "Lille kobbersneppe",
    name_en: "Bar-tailed godwit",
    latin: "Limosa lapponica",
    images: ["/images/fugle/vadefugle/lillekobbersneppe_1.jpg", "/images/fugle/vadefugle/lillekobbersneppe_2.jpg"],
    weight: "190–400 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Svagt opadbøjet næb og en hvid kile i ryggen — stor kobbersneppe er en del større og har et tydeligt hvidt vingebånd i flugt.",
    confusedWith: ["storkobbersneppe"],
    features: [
      "Bill about 10 cm long, clearly but slightly upturned",
      "Red in summer plumage, grey in winter",
      "White wedge up the back",
      "No white wing bar — unlike the black-tailed godwit",
    ],
  },
  {
    id: "lilleregnspove",
    category: "vadefugle",
    name_da: "Lille regnspove",
    name_en: "Whimbrel",
    latin: "Numenius phaeopus",
    images: [
      "/images/fugle/vadefugle/lilleregnspove_1.jpg",
      "/images/fugle/vadefugle/lilleregnspove_2.jpg",
      "/images/fugle/vadefugle/lilleregnspove_3.jpg",
    ],
    weight: "270–450 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "En lys og to mørke længdestriber på hovedet — stor regnspove er lidt større og har længere næb.",
    confusedWith: ["storregnspove"],
    features: [
      "Long, downcurved bill, long legs and long neck",
      "Brown plumage with black lengthwise streaks",
      "One pale and two dark stripes on the head",
      "Slightly smaller and shorter-billed than the curlew",
    ],
  },
  {
    id: "roedben",
    category: "vadefugle",
    name_da: "Rødben",
    name_en: "Common redshank",
    latin: "Tringa totanus",
    images: ["/images/fugle/vadefugle/roedben_1.jpg", "/images/fugle/vadefugle/roedben_2.jpg"],
    weight: "85–155 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Røde ben, lige halvlangt næb med rødlig basis og hvide felter på bagvingen — hvidkliren har grønne ben.",
    confusedWith: ["hvidklirre", "sortklirre"],
    features: [
      "Red legs",
      "Straight, medium-length bill with a reddish base",
      "White patches on the trailing edge of the wing and a white wedge up the back",
      "Greyish upper side with a paler belly and breast streaked with black",
    ],
  },
  {
    id: "skovsneppe",
    category: "vadefugle",
    name_da: "Skovsneppe",
    name_en: "Eurasian woodcock",
    latin: "Scolopax rusticola",
    images: [
      "/images/fugle/vadefugle/skovsneppe_1.jpg",
      "/images/fugle/vadefugle/skovsneppe_2.jpg",
      "/images/fugle/vadefugle/skovsneppe_3.jpg",
    ],
    weight: "240–420 g",
    habitat: "loevskov",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Brun, vatret vadefugl med rundt hoved og 3–4 tværgående mørke bånd over issen — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Brown wader, mottled with dark and light-brown markings",
      "Round head with 3–4 dark-brown bands across the crown",
      "Long, straight bill and short legs",
      "A woodland bird, mainly active at night — males make a ‘roding’ display flight at dusk in spring and summer",
    ],
  },
  {
    id: "sortklirre",
    category: "vadefugle",
    name_da: "Sortklire",
    name_en: "Spotted redshank",
    latin: "Tringa erythropus",
    images: ["/images/fugle/vadefugle/sortklirre_2.jpg"],
    weight: "97–160 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 4,
    native: true,
    differentiator: "Helt sort med sorte ben i sommerdragt, lys med røde ben om vinteren — hvidkliren har grønne ben.",
    confusedWith: ["hvidklirre", "roedben"],
    features: [
      "Long bill",
      "Summer plumage: black, with black legs",
      "Winter plumage: pale, with red legs",
      "In winter easily confused with the redshank",
    ],
  },
  {
    id: "storkobbersneppe",
    category: "vadefugle",
    name_da: "Stor kobbersneppe",
    name_en: "Black-tailed godwit",
    latin: "Limosa limosa",
    images: [
      "/images/fugle/vadefugle/storkobbersneppe_1.jpg",
      "/images/fugle/vadefugle/storkobbersneppe_2.jpg",
      "/images/fugle/vadefugle/storkobbersneppe_3.jpg",
    ],
    weight: "280–500 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Tydeligt hvidt vingebånd i flugt — lille kobbersneppe mangler det og er en del mindre.",
    confusedWith: ["lillekobbersneppe"],
    features: [
      "Bill 10–12 cm long, slightly upturned",
      "Red in summer plumage, grey in winter",
      "Clear white wing bar (only visible in flight)",
      "Larger than the bar-tailed godwit",
    ],
  },
  {
    id: "storregnspove",
    category: "vadefugle",
    name_da: "Stor regnspove",
    name_en: "Eurasian curlew",
    latin: "Numenius arquata",
    images: [
      "/images/fugle/vadefugle/storregnspove_1.jpg",
      "/images/fugle/vadefugle/storregnspove_2.jpg",
      "/images/fugle/vadefugle/storregnspove_3.jpg",
    ],
    weight: "575–1000 g",
    habitat: "vadehavet",
    activity: "day",
    rarity: 3,
    native: true,
    differentiator: "Meget langt, nedadbøjet næb — lille regnspove er mindre, har kortere næb og striber på hovedet.",
    confusedWith: ["lilleregnspove"],
    features: [
      "Long, downcurved bill, long legs and long neck",
      "Brown plumage with black lengthwise streaks",
      "A large wader, often seen in small flocks on sand flats and meadows",
      "Breeds in small numbers on heaths and heath bogs in Jutland",
    ],
  },
  {
    id: "strandskade",
    category: "vadefugle",
    name_da: "Strandskade",
    name_en: "Eurasian oystercatcher",
    latin: "Haematopus ostralegus",
    images: ["/images/fugle/vadefugle/strandskade_1.jpg", "/images/fugle/vadefugle/strandskade_2.jpg"],
    weight: "400–700 g",
    habitat: "kystvand",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sort og hvid med et kraftigt, langt, lige rødt næb og røde ben — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Black head, breast and upper side, white underside",
      "Strong, long, straight red bill",
      "Red legs",
      "Cannot be confused with any other species",
    ],
  },
  {
    id: "vibe",
    category: "vadefugle",
    name_da: "Vibe",
    name_en: "Northern lapwing",
    latin: "Vanellus vanellus",
    images: ["/images/fugle/vadefugle/vibe_1.jpg", "/images/fugle/vadefugle/vibe_2.jpg"],
    weight: "150–300 g",
    habitat: "landbrugsland",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Tydelig mørk top på hovedet og mørk grøn ryg — i flugt sorte, runde vinger med hvid underside.",
    confusedWith: [],
    features: [
      "Clear dark crest",
      "Dark-green upper side",
      "Short dark bill and short legs; black breast and neck, white belly",
      "From below in flight: black, rounded wings with white undersides and a black bib",
    ],
  },

  // --- Vandhøns (rails & coots) ---
  {
    id: "blishoene",
    category: "vandhoens",
    name_da: "Blishøne",
    name_en: "Eurasian coot",
    latin: "Fulica atra",
    images: ["/images/fugle/vandhoens/blishoene.jpg", "/images/fugle/vandhoens/blishoene_2.jpg"],
    weight: "560–810 g",
    habitat: "soeer",
    activity: "day",
    rarity: 1,
    native: true,
    differentiator: "Sodsort med en tydelig hvid blis i panden — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Clear white frontal shield (blis)",
      "Sooty black plumage",
      "Breeds in almost every lake, bog and wetland in Denmark",
      "Gathers in very large flocks in fjords and bays in autumn and winter",
    ],
  },
  {
    id: "groenbenetroerhoene",
    category: "vandhoens",
    name_da: "Grønbenet rørhøne",
    name_en: "Common moorhen",
    latin: "Gallinula chloropus",
    images: ["/images/fugle/vandhoens/groenbenetroerhoene_1.jpg", "/images/fugle/vandhoens/groenbenetroerhoene_2.jpg"],
    weight: "250–400 g",
    habitat: "vaadomrader",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Tydelig rød blis og rødt-gult næb på en sodsort krop med hvidt i vingen og på halen.",
    confusedWith: [],
    features: [
      "Clear red frontal shield",
      "Red and yellow bill",
      "Sooty black with white in the wing",
      "White on the tail",
    ],
  },
];

export default SPECIES;
