// All animals used in the quiz, grouped by category (see categories.js).
//
// TO ADD A PHOTO: drop an image file into
// public/images/pattedyr/<category>/ and list its path in the
// `images` array below, e.g.
// public/images/pattedyr/hundedyr/raev_1.jpg -> "/images/pattedyr/hundedyr/raev_1.jpg".
// (The "pattedyr" (mammals) level exists so a future group, like
// "fugle" for birds, can sit alongside it without reshuffling this one.)
// You can list more than one photo per species — the quiz picks a
// random one from the list each time that species comes up. If
// `images` is empty, a placeholder sketch is shown instead.
//
// Extra fields used by the post-answer "stats" and "kendetegn" boxes:
//   habitat        one of the fixed biome ids in biomes.js
//   activity       "day" | "night" | "both" (both = crepuscular/no strong pattern)
//   rarity         1 (extremely common) – 5 (very rare/localised), relative
//                  to Denmark — shown in the FAKTA box as that many dots.
//                  These are rough, best-effort estimates for gameplay
//                  flavour, not official population data.
//   native         true if naturally occurring in Denmark, false if
//                  introduced/escaped (regardless of how long established)
//   differentiator one short, punchy sentence: the single best way to
//                  tell it apart from whatever it's most often confused
//                  with (used instead of a long feature list, since the
//                  goal is one memorable fact, not a wall of text)

const SPECIES = [
  // --- Hjortevildt (deer) ---
  {
    id: "raadyr",
    category: "hjortevildt",
    name_da: "Rådyr",
    name_en: "Roe deer",
    latin: "Capreolus capreolus",
    images: [
      "/images/pattedyr/hjortevildt/raadyr_1.jpg",
      "/images/pattedyr/hjortevildt/raadyr_2.jpg",
      "/images/pattedyr/hjortevildt/raadyr_3.jpg",
      "/images/pattedyr/hjortevildt/raadyr_4.jpg",
    ],
    weight: "20–30 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Lille, spinkel krop med et rent hvidt spejl uden sort kant — dådyret har en tydelig sort kant om spejlet.",
    features: [
      "Denmark's smallest deer — roughly the size of a large dog",
      "Pure white rump patch (spejl), with no black edge — and the short tail is barely visible",
      "Bucks carry small antlers, up to three points, grown in “bast” and cleaned by spring",
      "Solitary or in small family groups, and strongly territorial",
    ],
  },
  {
    id: "daadyr",
    category: "hjortevildt",
    name_da: "Dådyr",
    name_en: "Fallow deer",
    latin: "Dama dama",
    images: [
      "/images/pattedyr/hjortevildt/daadyr_1.jpg",
      "/images/pattedyr/hjortevildt/daadyr_2.jpg",
      "/images/pattedyr/hjortevildt/daadyr_3.jpg",
    ],
    weight: "30–35 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 3,
    native: false,
    differentiator: "Det brede, skovlformede gevir er unikt blandt de danske hjorte — intet andet har den facon.",
    features: [
      "Summer coat is often reddish-brown with white spots — though colour varies widely, from near-white to near-black",
      "White rump patch with the most distinct black border of all four species, split by a black stripe on the tail",
      "Bucks grow broad, shovel-shaped (“palmate”) antlers — the only Danish deer with this shape",
      "Lives in herds; not native to Denmark, introduced centuries ago",
    ],
  },
  {
    id: "kronhjort",
    category: "hjortevildt",
    name_da: "Kronhjort",
    name_en: "Red deer",
    latin: "Cervus elaphus",
    images: [
      "/images/pattedyr/hjortevildt/krondyr_1.jpg",
      "/images/pattedyr/hjortevildt/krondyr_2.jpg",
      "/images/pattedyr/hjortevildt/krondyr_3.jpg",
    ],
    weight: "90–150 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 4,
    native: true,
    differentiator: "Danmarks største hjort — gulligt-brunt spejl helt uden sort kant, modsat både dådyr og sika.",
    features: [
      "Denmark's largest land mammal",
      "Pale, yellowish-brown rump patch — with no black edge, unlike fallow or sika",
      "Stags carry large, branching (not palmate) antlers — up to 20+ points on old animals",
      "Older stags grow a shaggy mane around the neck in winter",
    ],
  },
  {
    id: "sika",
    category: "hjortevildt",
    name_da: "Sikahjort",
    name_en: "Sika deer",
    latin: "Cervus nippon",
    images: ["/images/pattedyr/hjortevildt/sika_1.jpg", "/images/pattedyr/hjortevildt/sika_2.jpg"],
    weight: "30–35 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 5,
    native: false,
    differentiator: "Ligner et dådyr, men spejlets sorte kant er langt svagere, og den beholder ofte hvide pletter hele året.",
    features: [
      "Similar size to fallow deer, and easy to confuse with it",
      "Often keeps faint white spots even outside the summer coat",
      "White rump patch, but with a much fainter black edge than the fallow deer's",
      "Can flare the white rump hair outward when alarmed",
    ],
  },

  // --- Hundedyr (canids) ---
  {
    id: "ulv",
    category: "hundedyr",
    name_da: "Ulv",
    name_en: "Wolf",
    latin: "Canis lupus",
    images: ["/images/pattedyr/hundedyr/ulv_1.jpg", "/images/pattedyr/hundedyr/ulv_2.jpg"],
    weight: "30–50 kg",
    habitat: "naaleskov",
    activity: "night",
    rarity: 5,
    native: true,
    differentiator: "Højere i skulderen og mere langbenet end en ræv, med en lige hængende hale — ræven har en busket hale med hvid spids.",
    features: [
      "Denmark's largest wild canid — noticeably taller at the shoulder and longer-legged than a fox",
      "Grey-brown coat with a bushy tail carried low and straight, never curled up",
      "Moves in a direct, ground-covering trot rather than a fox's quicker trotting gait",
      "Still rare in Denmark — a small population has been reestablishing itself since 2012",
    ],
  },
  {
    id: "raev",
    category: "hundedyr",
    name_da: "Rødræv",
    name_en: "Red fox",
    latin: "Vulpes vulpes",
    images: ["/images/pattedyr/hundedyr/raev_1.jpg", "/images/pattedyr/hundedyr/raev_2.jpg"],
    weight: "5–8 kg",
    habitat: "landbrugsland",
    activity: "night",
    rarity: 1,
    native: true,
    differentiator: "Rødlig-orange pels med sorte ben og en busket, hvidspidset hale — langt mindre og spinklere end en ulv.",
    features: [
      "Denmark's most common wild canid — found in forests, farmland, and cities alike",
      "Reddish-orange coat with black legs and ear-backs, and a bushy white-tipped tail",
      "Much smaller and slighter than a wolf, with a pointed muzzle and upright triangular ears",
      "Mostly active at dusk and night, usually hunting alone for rodents and birds",
    ],
  },

  // --- Mårvildt (mustelids, + a couple of invasive lookalikes) ---
  {
    id: "graevling",
    category: "maarvildt",
    name_da: "Grævling",
    name_en: "Badger",
    latin: "Meles meles",
    images: ["/images/pattedyr/maarvildt/graevling_1.jpg"],
    weight: "10–20 kg",
    habitat: "loevskov",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "Det sort-hvide stribede ansigt er umiskendeligt — intet andet dansk pattedyr ligner den.",
    features: [
      "Unmistakable black-and-white striped face, stocky grey body, short powerful digging legs",
      "Lives in large underground burrow systems (grav) reused by the same family for generations",
      "Mostly nocturnal and omnivorous, eating anything from earthworms to fruit",
      "Heaviest in autumn, building up fat reserves before winter",
    ],
  },
  {
    id: "ilder",
    category: "maarvildt",
    name_da: "Ilder",
    name_en: "European polecat",
    latin: "Mustela putorius",
    images: ["/images/pattedyr/maarvildt/ilder_1.jpg", "/images/pattedyr/maarvildt/ilder_2.jpg"],
    weight: "0.5–1.5 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Mørk krop med en lys, maskeagtig plet om øjne og snude — minken er ensfarvet mørk uden den maske.",
    features: [
      "Dark brown-blackish body with a distinctive pale, mask-like patch around the eyes and muzzle",
      "Long, low-slung weasel-family body with a bushy dark tail",
      "Mostly nocturnal, often found near water, farms, and rabbit warrens",
      "Males are noticeably larger than females",
    ],
  },
  {
    id: "brud",
    category: "maarvildt",
    name_da: "Brud",
    name_en: "Weasel",
    latin: "Mustela nivalis",
    images: ["/images/pattedyr/maarvildt/brud_1.jpg", "/images/pattedyr/maarvildt/brud_2.jpg"],
    weight: "30–130 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Danmarks mindste rovdyr — kortere hale end en lækat, og halen mangler dens sorte spids.",
    features: [
      "Denmark's smallest carnivore — barely bigger than the mice and voles it hunts",
      "Thinner and shorter-tailed than a stoat, with no black tip on the tail",
      "Reddish-brown back with a sharply defined white underside",
      "Fast, low-slung hunter that can follow rodents straight into their burrows",
    ],
  },
  {
    id: "laekat",
    category: "maarvildt",
    name_da: "Lækat",
    name_en: "Stoat",
    latin: "Mustela erminea",
    images: ["/images/pattedyr/maarvildt/laekat_1.jpg", "/images/pattedyr/maarvildt/laekat_2.jpg"],
    weight: "150–450 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 4,
    native: true,
    differentiator: "Ligner en brud, men er større og har en tydelig sort spids på halen — det er hele kendetegnet.",
    features: [
      "Similar to the weasel but larger, with a distinctly black-tipped tail — the key giveaway",
      "Reddish-brown back and white underside, with a sharp border between the two",
      "In colder parts of its range it turns partly or fully white in winter — rare in Denmark",
      "Hunts rabbits and rodents much larger than itself",
    ],
  },
  {
    id: "husmaar",
    category: "maarvildt",
    name_da: "Husmår",
    name_en: "Stone marten",
    latin: "Martes foina",
    images: ["/images/pattedyr/maarvildt/husmaar_1.jpg"],
    weight: "1.5–2.5 kg",
    habitat: "beboelse",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Lyserød næse og en hvid strubeplet, der når ud på forbenene — skovmåren har mørk næse og gullig plet.",
    features: [
      "Grey-brown coat with a white/cream throat patch that reaches out onto the front legs",
      "Pink nose, unlike the pine marten's darker nose",
      "Often lives close to or inside buildings in towns and villages",
      "Agile climber, active mostly at night",
    ],
  },
  {
    id: "skovmaar",
    category: "maarvildt",
    name_da: "Skovmår",
    name_en: "Pine marten",
    latin: "Martes martes",
    images: ["/images/pattedyr/maarvildt/skovmaar_1.jpg", "/images/pattedyr/maarvildt/skovmaar_2.jpg"],
    weight: "1–2 kg",
    habitat: "loevskov",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Gullig (ikke hvid) strubeplet og mørk næse — husmåren har en hvid plet og lyserød næse.",
    features: [
      "Similar to the stone marten, but with a yellowish (not white) throat patch and a dark nose",
      "Chocolate-brown coat and a bushy tail",
      "More strictly tied to woodland than the stone marten, and an agile climber",
      "Mostly active at dusk and night",
    ],
  },
  {
    id: "odder",
    category: "maarvildt",
    name_da: "Odder",
    name_en: "Eurasian otter",
    latin: "Lutra lutra",
    images: ["/images/pattedyr/maarvildt/odder_1.jpg", "/images/pattedyr/maarvildt/odder_2.jpg"],
    weight: "6–12 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Stor, helt akvatisk måredyr med en tyk, tilspidset hale — minken er meget mindre og slankere.",
    features: [
      "Large, streamlined, fully aquatic mustelid with a thick, tapering tail",
      "Dense brown fur, pale throat, small ears, and long whiskers",
      "Leaves distinctive slides and webbed, 5-toed tracks along riverbanks",
      "Needs clean rivers and lakes with healthy fish stocks",
    ],
  },
  {
    id: "mink",
    category: "maarvildt",
    name_da: "Mink",
    name_en: "American mink",
    latin: "Neovison vison",
    images: ["/images/pattedyr/maarvildt/mink_1.png"],
    weight: "0.7–1.6 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 3,
    native: false,
    differentiator: "Slank, ensfarvet mørkebrun krop, ofte med hvid hageplet — meget mindre og slankere end odderen.",
    features: [
      "Slim, dark chocolate-brown body, often with a small white patch on the chin",
      "Semi-aquatic — a strong swimmer found along streams, lakes, and coasts",
      "An invasive species in Denmark, descended from animals escaped or released from fur farms",
      "Smaller and slimmer than an otter, with a thinner tail",
    ],
  },
  {
    id: "maarhund",
    category: "maarvildt",
    name_da: "Mårhund",
    name_en: "Raccoon dog",
    latin: "Nyctereutes procyonoides",
    images: ["/images/pattedyr/maarvildt/maarhund_1.jpg"],
    weight: "4–10 kg",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 4,
    native: false,
    differentiator: "Ligner en vaskebjørn med sin sorte ansigtsmaske, men mangler den ringede hale og har kortere ben.",
    features: [
      "Actually a canid, despite its raccoon-like black face mask and stocky build",
      "Short legs, bushy tail, and a distinctive dark mask across the eyes",
      "An invasive species in Denmark, actively controlled to protect native wildlife",
      "Unlike foxes, it can't run fast and often freezes or plays dead when threatened",
    ],
  },
  {
    id: "vaskebjoern",
    category: "maarvildt",
    name_da: "Vaskebjørn",
    name_en: "Raccoon",
    latin: "Procyon lotor",
    images: ["/images/pattedyr/maarvildt/vaskebjoern_1.jpg"],
    weight: "4–9 kg",
    habitat: "beboelse",
    activity: "night",
    rarity: 5,
    native: false,
    differentiator: "Den ringede, buskede hale er unik — mårhunden ligner ansigtet, men har ikke den ringede hale.",
    features: [
      "Not native to Denmark — an escaped/introduced species, unrelated to the native mustelids",
      "Black facial \"bandit\" mask and a bushy, ringed tail",
      "Stocky grey-brown body with dexterous front paws, and a flat-footed, shuffling walk",
      "Climbs well and is mostly active at night",
    ],
  },

  // --- Sæler (seals) ---
  {
    id: "graasael",
    category: "saeler",
    name_da: "Gråsæl",
    name_en: "Grey seal",
    latin: "Halichoerus grypus",
    images: ["/images/pattedyr/saeler/graa_1.jpg", "/images/pattedyr/saeler/graa_2.jpg", "/images/pattedyr/saeler/graa_3.jpg"],
    weight: "150–300 kg",
    habitat: "kystvand",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Lang, lige \"romersk\" næseprofil med parallelle næsebor — spættet sæl har en kort, rund hundesnude.",
    features: [
      "Denmark's largest seal, with a long, straight \"Roman nose\" profile",
      "Blotchy, irregular coat pattern that varies widely between individuals",
      "Nostrils are widely spaced and run roughly parallel to each other",
      "Males are much larger than females",
    ],
  },
  {
    id: "spaettetsael",
    category: "saeler",
    name_da: "Spættet sæl",
    name_en: "Harbor seal",
    latin: "Phoca vitulina",
    images: ["/images/pattedyr/saeler/spaettet_1.jpg", "/images/pattedyr/saeler/spaettet_2.jpg", "/images/pattedyr/saeler/spaettet_3.jpg"],
    weight: "45–130 kg",
    habitat: "kystvand",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Kort, rund hundeagtig snude med V-formede næsebor — gråsælen har en lang, lige næseprofil.",
    features: [
      "Smaller and more common than the grey seal, with a short, rounded, dog-like face",
      "Nostrils form a distinct V-shape, close together at the bottom",
      "Fine, evenly distributed spots over a grey coat — hence the Danish name",
      "Often hauls out on sandbanks in groups at low tide",
    ],
  },

  // --- Gnavere (rodents, + hare/rabbit and a couple of insectivores) ---
  {
    id: "kanin",
    category: "gnavere",
    name_da: "Vildkanin",
    name_en: "Rabbit",
    latin: "Oryctolagus cuniculus",
    images: ["/images/pattedyr/gnavere/vildkanin_1.jpg", "/images/pattedyr/gnavere/vildkanin_2.jpg"],
    weight: "1.3–2.2 kg",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 2,
    native: false,
    differentiator: "Mindre end en hare med kortere bagben og rundere ører — og gemmer sig i jordhuler, det gør haren aldrig.",
    features: [
      "Smaller than a hare, with shorter hind legs and rounder ears relative to its head",
      "Lives underground in dug burrow systems (kaninbo), often in colonies — hares never dig burrows",
      "Fairly uniform greyish-brown coat with a short, pale, cottony tail",
      "When startled, tends to freeze or dash for the nearest burrow rather than sprint across open ground",
    ],
  },
  {
    id: "hare",
    category: "gnavere",
    name_da: "Hare",
    name_en: "European hare",
    latin: "Lepus europaeus",
    images: ["/images/pattedyr/gnavere/hare_1.jpg", "/images/pattedyr/gnavere/hare_2.jpg"],
    weight: "3–5 kg",
    habitat: "landbrugsland",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "Større end en kanin med lange sortspidsede ører og kraftige bagben — lever aldrig i en jordhule.",
    features: [
      "Larger than a rabbit, with long black-tipped ears and long, powerful hind legs",
      "Lives alone above ground in a shallow scrape (sæde), never in a burrow",
      "Sprints in fast bursts and jinks sharply from side to side to escape predators",
      "Reddish-brown coat, visibly larger and rangier-looking than a rabbit",
    ],
  },
  {
    id: "baever",
    category: "gnavere",
    name_da: "Bæver",
    name_en: "Eurasian beaver",
    latin: "Castor fiber",
    images: ["/images/pattedyr/gnavere/baever_1.jpg"],
    weight: "15–30 kg",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 5,
    native: true,
    differentiator: "Danmarks største gnaver, med en bred, flad, skælklædt padle-hale — sumpbæverens hale er rund, ikke flad.",
    features: [
      "Denmark's largest rodent, with a broad, flat, scaly, paddle-shaped tail",
      "Webbed hind feet for swimming, and small eyes/ears set high on the head",
      "Builds dams, lodges, and canals — look for tree stumps gnawed to a pencil point",
      "Purely vegetarian, feeding on bark, twigs, and water plants",
    ],
  },
  {
    id: "bisamrotte",
    category: "gnavere",
    name_da: "Bisamrotte",
    name_en: "Muskrat",
    latin: "Ondatra zibethicus",
    images: ["/images/pattedyr/gnavere/bisamrotte_1.jpg"],
    weight: "0.7–1.8 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 4,
    native: false,
    differentiator: "Meget mindre end en bæver, med en tynd hale der er flad fra siderne — sumpbæverens hale er rund.",
    features: [
      "Much smaller than a beaver, with a long, thin tail flattened side-to-side, not paddle-shaped",
      "Dark brown fur, partially webbed hind feet, and a blunt, rounded head",
      "An invasive species in Denmark, semi-aquatic in ponds, ditches, and slow rivers",
      "Swims with mostly its head above water, tail trailing or sculling behind",
    ],
  },
  {
    id: "sumpbaever",
    category: "gnavere",
    name_da: "Sumpbæver",
    name_en: "Coypu",
    latin: "Myocastor coypus",
    images: ["/images/pattedyr/gnavere/sumpbaever_1.jpg", "/images/pattedyr/gnavere/sumpbaever_2.jpg"],
    weight: "5–9 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 5,
    native: false,
    differentiator: "Lang, rund, rotteagtig hale (hverken flad som bæver eller bisamrotte) og store, orange fortænder.",
    features: [
      "Between muskrat and beaver in size, with a long, round, rat-like tail — not flattened",
      "Distinctive large, bright orange front teeth",
      "White muzzle and whiskers standing out against a dark brown coat",
      "An invasive species escaped from fur farms; actively controlled in Denmark",
    ],
  },
  {
    id: "egern",
    category: "gnavere",
    name_da: "Egern",
    name_en: "Red squirrel",
    latin: "Sciurus vulgaris",
    images: ["/images/pattedyr/gnavere/egern_1.jpg"],
    weight: "250–350 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Det eneste af de små gnavere, der er aktivt om dagen og klatrer i træer — kendes på den buskede hale.",
    features: [
      "Reddish-brown coat (can vary to almost black), with a bushy tail and ear tufts, especially in winter",
      "Agile tree-climber, active during the day — unlike most small rodents",
      "Builds round nests (dreys) high up in tree branches",
      "Buries nuts and seeds for winter, often in many small caches",
    ],
  },
  {
    id: "markmus",
    category: "gnavere",
    name_da: "Markmus",
    name_en: "Field vole",
    latin: "Microtus agrestis",
    images: ["/images/pattedyr/gnavere/markmus_1.jpg"],
    weight: "20–40 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Kort hale og en stump, rund snude (ikke en mus' spidse ansigt) — og meget mindre end en mosegris.",
    features: [
      "Small, stocky body with a short tail, small ears, and a blunt rounded snout — unlike a mouse's pointed face",
      "Greyish-brown fur, living in grassland and field edges under thick vegetation",
      "Makes visible surface runways through grass, rather than living mainly underground",
      "A key prey species for owls, foxes, and weasels",
    ],
  },
  {
    id: "mosegris",
    category: "gnavere",
    name_da: "Mosegris",
    name_en: "Water vole",
    latin: "Arvicola amphibius",
    images: ["/images/pattedyr/gnavere/mosegris_1.jpg"],
    weight: "150–300 g",
    habitat: "soeer",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Samme stumpe ansigt som en markmus, men meget større, og lever ved vand i stedet for på tørre marker.",
    features: [
      "Much larger and stockier than a field vole, with a blunt face and small ears hidden in the fur",
      "Furry tail (not naked and scaly like a rat's), roughly half its body length",
      "Semi-aquatic, digging burrows into stream and pond banks",
      "Often mistaken for a rat, but rounder-faced and much less pointed at the nose",
    ],
  },
  {
    id: "skovmus",
    category: "gnavere",
    name_da: "Skovmus",
    name_en: "Wood mouse",
    latin: "Apodemus sylvaticus",
    images: ["/images/pattedyr/gnavere/skovmus.jpg"],
    weight: "13–27 g",
    habitat: "loevskov",
    activity: "night",
    rarity: 1,
    native: true,
    differentiator: "Ægte mus med store øjne/ører og en hale lige så lang som kroppen — meget mindre end en rotte.",
    features: [
      "Small true mouse with large dark eyes and ears, and a tail about as long as its body",
      "Sandy-brown back with a clean white belly and a small yellowish chest patch",
      "Excellent jumper, common in gardens, fields, and woodland",
      "Much smaller and lighter than a rat, with a proportionally longer tail",
    ],
  },
  {
    id: "rotte",
    category: "gnavere",
    name_da: "Rotte",
    name_en: "Brown rat",
    latin: "Rattus norvegicus",
    images: ["/images/pattedyr/gnavere/rotte_1.jpg"],
    weight: "200–500 g",
    habitat: "beboelse",
    activity: "night",
    rarity: 1,
    native: false,
    differentiator: "Meget større end skovmus og markmus, med en tyk, nøgen hale der er kortere end kroppen.",
    features: [
      "Much larger than any native mouse or vole, with a thick, scaly, naked tail shorter than its body",
      "Blunt nose, small ears, and a heavy, robust build",
      "Common around farms, waterways, sewers, and urban areas",
      "Highly adaptable omnivore, active mostly at night",
    ],
  },
  {
    id: "muldvarp",
    category: "gnavere",
    name_da: "Muldvarp",
    name_en: "European mole",
    latin: "Talpa europaea",
    images: ["/images/pattedyr/gnavere/muldvarp_1.jpg"],
    weight: "70–130 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Cylindrisk, fløjlssort krop uden synlige ører — de skovlformede forpoter er umiskendelige.",
    features: [
      "Cylindrical, velvety black body built for tunneling, with no visible external ears",
      "Large, spade-like, outward-turned front paws for digging",
      "Tiny eyes mostly hidden by fur — spends almost its entire life underground",
      "Its molehills of loose soil are usually the only visible sign of it",
    ],
  },
  {
    id: "pindsvin",
    category: "gnavere",
    name_da: "Pindsvin",
    name_en: "European hedgehog",
    latin: "Erinaceus europaeus",
    images: ["/images/pattedyr/gnavere/pindsvin_1.jpg"],
    weight: "400–1200 g",
    habitat: "beboelse",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "Det piggede ryg og evnen til at rulle sig sammen er unikt — intet andet dansk dyr ligner den.",
    features: [
      "Entire back and sides covered in short, stiff spines; rolls into a ball when threatened",
      "Small pointed face and short legs, mostly nocturnal",
      "Snuffles noisily through leaf litter and garden undergrowth hunting insects and slugs",
      "Hibernates through the coldest months, often in piles of leaves or brush",
    ],
  },

  // --- Andet (wild boar and mouflon) ---
  {
    id: "vildsvin",
    category: "andet",
    name_da: "Vildsvin",
    name_en: "Wild boar",
    latin: "Sus scrofa",
    images: ["/images/pattedyr/andet/vildsvin_1.jpg", "/images/pattedyr/andet/vildsvin_2.jpg", "/images/pattedyr/andet/vildsvin_3.jpg"],
    weight: "50–150 kg",
    habitat: "naaleskov",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Grisagtig krop med et kraftigt hoved — langt tungere og mere firkantet bygget end en muflon.",
    features: [
      "Stocky pig-shaped body with a large head, small eyes, and short legs",
      "Coarse, dark, bristly coat — piglets are pale with brown stripes",
      "Roots through soil with its snout to find roots, bulbs, and grubs",
      "Males (grow tusks) are much larger and heavier than females",
    ],
  },
  {
    id: "muflon",
    category: "andet",
    name_da: "Muflon",
    name_en: "Mouflon",
    latin: "Ovis gmelini musimon",
    images: ["/images/pattedyr/andet/muflon_1.jpg"],
    weight: "25–50 kg",
    habitat: "loevskov",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Et vildfår med krøllede horn hos vædderne — slankere og mere fåreagtigt bygget end et vildsvin.",
    features: [
      "A wild sheep, not a deer — introduced to Denmark for hunting",
      "Rams carry large, curling horns; ewes are usually hornless or have small horns",
      "Reddish-brown coat with a dark saddle patch and pale flank markings on rams",
      "Lives in herds on heathland and in forests with open clearings",
    ],
  },
];

export default SPECIES;
