import { asset } from "./asset.js";
// All animals used in the quiz, grouped by category (see categories.js).
//
// TO ADD A PHOTO: drop the original into photos/pattedyr/<category>/,
// run `npm run photos` (makes the web-sized copies in public/images/),
// and list the .webp path in the `images` array below, e.g.
// photos/pattedyr/hundedyr/raev_1.jpg -> "/images/pattedyr/hundedyr/raev_1.webp".
// (The "pattedyr" (mammals) level exists so a future group, like
// "fugle" for birds, can sit alongside it without reshuffling this one.)
// You can list more than one photo per species — the quiz picks a
// random one from the list each time that species comes up. If
// `images` is empty, a placeholder sketch is shown instead.
//
// Extra fields used by the post-answer "stats" and "kendetegn" boxes:
//   habitat        one of the fixed biome ids in biomes.js
//   activity       "day" | "night" | "both" (both = crepuscular/no strong pattern)
//   rarity         1 (extremely common) – 5 (very rare/localised), relative
//                  to Denmark — shown in the FAKTA box as that many dots.
//                  These are rough, best-effort estimates for gameplay
//                  flavour, not official population data.
//   native         true if naturally occurring in Denmark, false if
//                  introduced/escaped (regardless of how long established)
//   differentiator one short, punchy sentence: the single best way to
//                  tell it apart from whatever it's most often confused
//                  with (used instead of a long feature list, since the
//                  goal is one memorable fact, not a wall of text)
//   confusedWith   ids of the species in this file it's most easily
//                  mixed up with ("Forveksling") — empty if none
//
// Kendetegn, forveksling and (where given) weights are taken from the
// "Vildt & Jagt" handbook (chapter 2, Pattedyr). Species the book
// doesn't cover (ulv, brud, markmus, mosegris, skovmus, rotte,
// muldvarp, pindsvin) keep their earlier data.

const SPECIES = [
  // --- Hjortevildt (deer) ---
  {
    id: "raadyr",
    category: "hjortevildt",
    name_da: "Rådyr",
    name_en: "Roe deer",
    latin: "Capreolus capreolus",
    images: [
      "/images/pattedyr/hjortevildt/raadyr_1.webp",
      "/images/pattedyr/hjortevildt/raadyr_2.webp",
      "/images/pattedyr/hjortevildt/raadyr_3.webp",
      "/images/pattedyr/hjortevildt/raadyr_4.webp",
    ],
    weight: "14–25 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Langt mindre end de andre hjorte, med hvidt spejl helt uden synlig hale — størst risiko for forveksling er med sika-, då- eller kronkalve.",
    confusedWith: ["sika", "daadyr", "kronhjort"],
    features: [
      "Red summer coat and grey winter coat with a pale throat patch — the change to summer coat starts in April/May",
      "White rump patch (spejl) with no visible tail — faint in summer, very distinct in winter",
      "Bucks carry small antlers (opsats), from a single spike up to six points, cast from late November to January",
      "In winter the doe has a clear tuft of hair below the rump patch (skørt); Denmark's most common deer",
    ],
  },
  {
    id: "daadyr",
    category: "hjortevildt",
    name_da: "Dådyr",
    name_en: "Fallow deer",
    latin: "Dama dama",
    images: [
      "/images/pattedyr/hjortevildt/daadyr_1.webp",
      "/images/pattedyr/hjortevildt/daadyr_2.webp",
      "/images/pattedyr/hjortevildt/daadyr_3.webp",
    ],
    weight: "30–35 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 3,
    native: false,
    differentiator: "Den lange, synlige, sorte hale, der deler det hvide spejl lodret i to (\"111\"), er det bedste kendetegn — og kun dåhjorten har skovlformet gevir.",
    confusedWith: ["sika", "kronhjort"],
    features: [
      "Long black tail splitting the white rump patch vertically in two — the “111” memory rule",
      "Coat colour varies a lot: dark with a pale belly, or light brown with pale spots — white individuals are common",
      "Bucks carry spike, branched or broad shovel-shaped (palmate) antlers",
      "Lives in herds; introduced to Denmark about 1,000 years ago",
    ],
  },
  {
    id: "kronhjort",
    category: "hjortevildt",
    name_da: "Kronhjort",
    name_en: "Red deer",
    latin: "Cervus elaphus",
    images: [
      "/images/pattedyr/hjortevildt/krondyr_1.webp",
      "/images/pattedyr/hjortevildt/krondyr_2.webp",
      "/images/pattedyr/hjortevildt/krondyr_3.webp",
    ],
    weight: "60–175 kg",
    habitat: "loevskov",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Gult til lysebrunt spejl, hvor halen falder i ét med spejlet — sika og dåvildt har hvidt spejl, og dåvildt en lang sort hale.",
    confusedWith: ["sika", "daadyr"],
    features: [
      "Denmark's largest deer — stags 90–175 kg, hinds 60–90 kg",
      "Yellowish to light-brown rump patch; the tail is rarely seen at a distance as it blends into it",
      "Red summer coat, grey-brown winter coat, and a noticeably long head on adults",
      "Stags carry large branching antlers (spike, branched or crowned); originally active by day, but mostly nocturnal in Denmark",
    ],
  },
  {
    id: "sika",
    category: "hjortevildt",
    name_da: "Sikahjort",
    name_en: "Sika deer",
    latin: "Cervus nippon",
    images: ["/images/pattedyr/hjortevildt/sika_1.webp", "/images/pattedyr/hjortevildt/sika_2.webp"],
    weight: "30–60 kg",
    habitat: "loevskov",
    activity: "both",
    rarity: 5,
    native: false,
    differentiator: "Hvidt spejl med en lille, ofte usynlig hale, der højst ses som en smal sort streg — dåvildtets sorte hale er lang og tydelig.",
    confusedWith: ["daadyr", "kronhjort"],
    features: [
      "White rump patch with a small, often invisible tail — at most a thin black line in the patch",
      "Dark coat with a pale belly",
      "Stags carry antlers with up to eight points",
      "Stags 50–60 kg, hinds 30–45 kg — hinds and calves are easily confused with fallow and red deer",
    ],
  },

  // --- Hundedyr (canids) ---
  {
    id: "ulv",
    category: "hundedyr",
    name_da: "Ulv",
    name_en: "Wolf",
    latin: "Canis lupus",
    images: ["/images/pattedyr/hundedyr/ulv_1.webp", "/images/pattedyr/hundedyr/ulv_2.webp"],
    weight: "30–50 kg",
    habitat: "naaleskov",
    activity: "night",
    rarity: 5,
    native: true,
    differentiator: "Højere i skulderen og mere langbenet end en ræv, med en lige hængende hale — ræven har en busket hale med hvid spids.",
    confusedWith: ["raev"],
    features: [
      "Denmark's largest wild canid — noticeably taller at the shoulder and longer-legged than a fox",
      "Grey-brown coat with a bushy tail carried low and straight, never curled up",
      "Moves in a direct, ground-covering trot rather than a fox's quicker trotting gait",
      "Still rare in Denmark — a small population has been reestablishing itself since 2012",
    ],
  },
  {
    id: "raev",
    category: "hundedyr",
    name_da: "Rødræv",
    name_en: "Red fox",
    latin: "Vulpes vulpes",
    images: ["/images/pattedyr/hundedyr/raev_1.webp", "/images/pattedyr/hundedyr/raev_2.webp"],
    weight: "6–10 kg",
    habitat: "landbrugsland",
    activity: "night",
    rarity: 1,
    native: true,
    differentiator: "Lang, busket lunte med lys spids, næsten lige så lang som kroppen — ulven er langt større og mangler den lyse halespids.",
    confusedWith: ["ulv"],
    features: [
      "Long bushy tail (lunte) with a pale tip, almost as long as the body",
      "Long-legged, with a pointed head",
      "Normally red, but darker and paler variants are common",
      "Found almost everywhere, including towns and summer-house areas — Denmark's most important predator of mammals and ground-nesting birds",
    ],
  },

  // --- Mårvildt (mustelids, + a couple of invasive lookalikes) ---
  {
    id: "graevling",
    category: "maarvildt",
    name_da: "Grævling",
    name_en: "Badger",
    latin: "Meles meles",
    images: ["/images/pattedyr/maarvildt/graevling_1.webp"],
    weight: "10–20 kg",
    habitat: "loevskov",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "To sorte, langsgående striber fra snuden over øjnene til ørerne — mårhund og vaskebjørn har i stedet en ansigtsmaske.",
    confusedWith: ["maarhund", "vaskebjoern"],
    features: [
      "Two black stripes running lengthwise from the snout over the eyes to the ears",
      "Short-legged and compact",
      "Grizzled grey coat — the same colouring as raccoon dog and raccoon",
      "Short tail, under a third of its body length, the same colour as the coat",
    ],
  },
  {
    id: "ilder",
    category: "maarvildt",
    name_da: "Ilder",
    name_en: "European polecat",
    latin: "Mustela putorius",
    images: ["/images/pattedyr/maarvildt/ilder_1.webp", "/images/pattedyr/maarvildt/ilder_2.webp"],
    weight: "0.5–1.5 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Et brunt bånd (maske) om øjnene afgrænset af hvide partier om den brune snude — minken er ensfarvet uden maske.",
    confusedWith: ["skovmaar", "husmaar", "mink"],
    features: [
      "Brown band across the eyes (a mask), framed by white patches around the brown snout",
      "Clear, pale underfur that shows through the darker guard hairs",
      "Long, low-slung weasel-family body with a bushy dark tail",
      "Easily confused with pine marten, stone marten and mink — the framed eye mask is the best clue",
    ],
  },
  {
    id: "brud",
    category: "maarvildt",
    name_da: "Brud",
    name_en: "Weasel",
    latin: "Mustela nivalis",
    images: ["/images/pattedyr/maarvildt/brud_1.webp", "/images/pattedyr/maarvildt/brud_2.webp"],
    weight: "30–130 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Danmarks mindste rovdyr — væsentligt mindre end en lækat, med en meget kort hale uden sort spids.",
    confusedWith: ["laekat"],
    features: [
      "Denmark's smallest carnivore — barely bigger than the mice and voles it hunts",
      "Thinner and much shorter-tailed than a stoat, with no black tip on the tail",
      "Reddish-brown back with a sharply defined white underside",
      "Fast, low-slung hunter that can follow rodents straight into their burrows",
    ],
  },
  {
    id: "laekat",
    category: "maarvildt",
    name_da: "Lækat",
    name_en: "Stoat",
    latin: "Mustela erminea",
    images: ["/images/pattedyr/maarvildt/laekat_1.webp", "/images/pattedyr/maarvildt/laekat_2.webp"],
    weight: "150–450 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 4,
    native: true,
    differentiator: "Halen har altid sort spids — både i den brune sommerdragt og den hvide vinterdragt; bruden er mindre og har en meget kort hale.",
    confusedWith: ["brud"],
    features: [
      "Summer coat: brown back and pale belly",
      "Winter coat: white",
      "The tail matches the season's coat, but always has a black tip",
      "Can be confused with a weasel in summer coat — the weasel is much smaller with a very short tail",
    ],
  },
  {
    id: "husmaar",
    category: "maarvildt",
    name_da: "Husmår",
    name_en: "Stone marten",
    latin: "Martes foina",
    images: ["/images/pattedyr/maarvildt/husmaar_1.webp"],
    weight: "1.3–1.7 kg",
    habitat: "beboelse",
    activity: "night",
    rarity: 3,
    native: true,
    differentiator: "Hvid strubeplet, der går ud på forbenene, og lys snude — skovmåren har gul strubeplet og mørkebrun snude.",
    confusedWith: ["skovmaar", "ilder"],
    features: [
      "White throat patch that extends out onto the front legs",
      "Pale snout and brownish-grey coat",
      "Looks shorter-legged than the pine marten, and climbs readily",
      "Usually lives near buildings — often in lofts, where it can damage insulation and thatched roofs; mostly active at dusk and night",
    ],
  },
  {
    id: "skovmaar",
    category: "maarvildt",
    name_da: "Skovmår",
    name_en: "Pine marten",
    latin: "Martes martes",
    images: ["/images/pattedyr/maarvildt/skovmaar_1.webp", "/images/pattedyr/maarvildt/skovmaar_2.webp"],
    weight: "1–2 kg",
    habitat: "loevskov",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Gul strubeplet, der ikke går ned på forbenene, og mørkebrun snude — husmåren har hvid plet ud på forbenene og lys snude.",
    confusedWith: ["husmaar", "ilder"],
    features: [
      "Yellow throat patch that rarely reaches down onto the front legs",
      "Dark brown snout",
      "Dark, chestnut-brown coat",
      "Looks a bit longer-legged with larger ears than the stone marten, and spends most of its time in trees",
    ],
  },
  {
    id: "odder",
    category: "maarvildt",
    name_da: "Odder",
    name_en: "Eurasian otter",
    latin: "Lutra lutra",
    images: ["/images/pattedyr/maarvildt/odder_1.webp", "/images/pattedyr/maarvildt/odder_2.webp"],
    weight: "6–12 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Lang krop med en lang, rund hale og små ører — i vandet kan den ligne sumpbæver, bæver og mink, men den er langt større end minken.",
    confusedWith: ["sumpbaever", "baever", "mink"],
    features: [
      "Long body with a long, round tail and small ears",
      "Dense, dark brown coat",
      "Often has paler patches on the throat",
      "Usually seen swimming, but also found on land along streams and lakes",
    ],
  },
  {
    id: "mink",
    category: "maarvildt",
    name_da: "Mink",
    name_en: "American mink",
    latin: "Neovison vison",
    images: ["/images/pattedyr/maarvildt/mink_1.webp"],
    weight: "0.75–1.5 kg",
    habitat: "soeer",
    activity: "day",
    rarity: 3,
    native: false,
    differentiator: "Ensfarvet sort eller mørkebrun uden lys underuld og uden maske — ilderen har både maske og lys underuld.",
    confusedWith: ["ilder", "odder"],
    features: [
      "Normally a uniform black or dark brown, with no pale underfur (several colour variants exist, even all white)",
      "Wild-type mink often have a white spot under the chin",
      "Males 1–1.5 kg, females about 0.75 kg",
      "Invasive — originally from North America and spread from fur farms; active by day, always near fresh or salt water",
    ],
  },
  {
    id: "maarhund",
    category: "maarvildt",
    name_da: "Mårhund",
    name_en: "Raccoon dog",
    latin: "Nyctereutes procyonoides",
    images: ["/images/pattedyr/maarvildt/maarhund_1.webp"],
    weight: "5–8 kg",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 4,
    native: false,
    differentiator: "Sort ansigtsmaske som vaskebjørnen, men en kort hale (under 1/3 af kroppen) uden ringe og sorte ben og underside.",
    confusedWith: ["vaskebjoern", "graevling"],
    features: [
      "Black mask around the eyes and a pointed head",
      "Short-legged, elongated body",
      "Black throat, underside and legs; long-haired grey-black upper side",
      "Short tail, under a third of its body length — invasive from East Asia, it can't climb trees and is controlled year-round",
    ],
  },
  {
    id: "vaskebjoern",
    category: "maarvildt",
    name_da: "Vaskebjørn",
    name_en: "Raccoon",
    latin: "Procyon lotor",
    images: ["/images/pattedyr/maarvildt/vaskebjoern_1.webp"],
    weight: "4–9 kg",
    habitat: "beboelse",
    activity: "night",
    rarity: 5,
    native: false,
    differentiator: "Den lange hale med 5–6 tydelige sorte ringe er unik — mårhunden har kort hale, og grævlingen har striber i stedet for maske.",
    confusedWith: ["maarhund", "graevling"],
    features: [
      "Black mask around the eyes",
      "Long tail with 5–6 distinct black rings",
      "Dark grey-brown coat",
      "Climbs trees readily — unlike the raccoon dog",
    ],
  },

  // --- Sæler (seals) ---
  {
    id: "graasael",
    category: "saeler",
    name_da: "Gråsæl",
    name_en: "Grey seal",
    latin: "Halichoerus grypus",
    images: ["/images/pattedyr/saeler/graa_1.webp", "/images/pattedyr/saeler/graa_2.webp", "/images/pattedyr/saeler/graa_3.webp"],
    weight: "150–300 kg",
    habitat: "kystvand",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Aflangt hoved med et langt snudeparti uden brat pandeovergang — spættet sæl har rundt hoved med brat overgang fra snude til pande.",
    confusedWith: ["spaettetsael"],
    features: [
      "Elongated head with a long, distinct muzzle",
      "No sharp step between snout and forehead",
      "Grey or brown coat with darker blotches",
      "Denmark's largest seal",
    ],
  },
  {
    id: "spaettetsael",
    category: "saeler",
    name_da: "Spættet sæl",
    name_en: "Harbor seal",
    latin: "Phoca vitulina",
    images: ["/images/pattedyr/saeler/spaettet_1.webp", "/images/pattedyr/saeler/spaettet_2.webp", "/images/pattedyr/saeler/spaettet_3.webp"],
    weight: "45–130 kg",
    habitat: "kystvand",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Rundt hoved med brat overgang fra snude til pande — gråsælen har et aflangt hoved med langt, lige snudeparti.",
    confusedWith: ["graasael"],
    features: [
      "Round head",
      "Sharp step between snout and forehead",
      "Greyish-white or greyish-yellow coat with numerous darker spots",
      "Smaller and more common than the grey seal",
    ],
  },

  // --- Gnavere (rodents, + hare/rabbit and a couple of insectivores) ---
  {
    id: "kanin",
    category: "gnavere",
    name_da: "Vildkanin",
    name_en: "Rabbit",
    latin: "Oryctolagus cuniculus",
    images: ["/images/pattedyr/gnavere/vildkanin_1.webp", "/images/pattedyr/gnavere/vildkanin_2.webp"],
    weight: "1.5–2 kg",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 2,
    native: false,
    differentiator: "Ørerne er kortere end hovedet og uden sorte spidser, og for- og bagben er næsten lige lange — haren har lange, sortspidsede ører og langt længere bagben.",
    confusedWith: ["hare"],
    features: [
      "Medium-length ears, shorter than the head, with no dark tips",
      "Light brown coat, but colour varies — Danish rabbits descend from releases",
      "Front and hind legs are almost the same length",
      "Lives in colonies, often in burrows; populations swing a lot because of myxomatosis",
    ],
  },
  {
    id: "hare",
    category: "gnavere",
    name_da: "Hare",
    name_en: "European hare",
    latin: "Lepus europaeus",
    images: ["/images/pattedyr/gnavere/hare_1.webp", "/images/pattedyr/gnavere/hare_2.webp"],
    weight: "ca. 4 kg",
    habitat: "landbrugsland",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "Ørerne er længere end hovedet og har sorte spidser, og oversiden af halen er sort — kaninen har kortere, ensfarvede ører.",
    confusedWith: ["kanin"],
    features: [
      "Long ears — longer than the head — with black tips",
      "The upper side of the tail (blomme) is black",
      "Grizzled grey-brown coat",
      "Hind legs much longer than the front legs; prefers open farmland where it rests in a shallow scrape (dagsæde)",
    ],
  },
  {
    id: "baever",
    category: "gnavere",
    name_da: "Bæver",
    name_en: "Eurasian beaver",
    latin: "Castor fiber",
    images: ["/images/pattedyr/gnavere/baever_1.webp"],
    weight: "15–30 kg",
    habitat: "vaadomrader",
    activity: "night",
    rarity: 5,
    native: true,
    differentiator: "Lang, bred, fladtrykt og hårløs hale — odder og sumpbæver har begge rund hale, men ligner bæveren meget i vandet.",
    confusedWith: ["odder", "sumpbaever", "bisamrotte"],
    features: [
      "Long, broad, flattened and hairless tail",
      "Grey-brown coat",
      "Body up to 75 cm — over 1 m including the tail",
      "Usually seen in the water or on the banks of streams and lakes",
    ],
  },
  {
    id: "bisamrotte",
    category: "gnavere",
    name_da: "Bisamrotte",
    name_en: "Muskrat",
    latin: "Ondatra zibethicus",
    images: ["/images/pattedyr/gnavere/bisamrotte_1.webp"],
    weight: "0.7–1.8 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 4,
    native: false,
    differentiator: "Langt mindre end bæver og sumpbæver — under 70 cm inkl. halen — så forvekslingen sker mest med unger af de to.",
    confusedWith: ["sumpbaever", "baever"],
    features: [
      "Long (20–28 cm) round to slightly flattened tail",
      "Brown coat",
      "Body up to 40 cm — under 70 cm including the tail",
      "Usually seen in the water or on the banks of shallow streams and lakes",
    ],
  },
  {
    id: "sumpbaever",
    category: "gnavere",
    name_da: "Sumpbæver",
    name_en: "Coypu",
    latin: "Myocastor coypus",
    images: ["/images/pattedyr/gnavere/sumpbaever_1.webp", "/images/pattedyr/gnavere/sumpbaever_2.webp"],
    weight: "5–9 kg",
    habitat: "soeer",
    activity: "night",
    rarity: 5,
    native: false,
    differentiator: "Lang, rund hale (30–45 cm) og ofte synlige orange fortænder — bæverens hale er bred og flad.",
    confusedWith: ["baever", "odder", "bisamrotte"],
    features: [
      "Long (30–45 cm) round tail",
      "Greyish-brown coat",
      "Body up to 60 cm — under 1 m including the tail",
      "The (orange) front teeth are often visible — in the water it's hard to tell from beaver and otter",
    ],
  },
  {
    id: "egern",
    category: "gnavere",
    name_da: "Egern",
    name_en: "Red squirrel",
    latin: "Sciurus vulgaris",
    images: ["/images/pattedyr/gnavere/egern_1.webp"],
    weight: "250–350 g",
    habitat: "loevskov",
    activity: "day",
    rarity: 2,
    native: true,
    differentiator: "Lang, busket hale, lys bug og ses mest oppe i træerne — kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Long, bushy tail",
      "Pale belly",
      "Normally reddish-brown, but dark brown and black individuals also occur",
      "Mostly seen up in the trees",
    ],
  },
  {
    id: "markmus",
    category: "gnavere",
    name_da: "Markmus",
    name_en: "Field vole",
    latin: "Microtus agrestis",
    images: ["/images/pattedyr/gnavere/markmus_1.webp"],
    weight: "20–40 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 1,
    native: true,
    differentiator: "Kort hale og en stump, rund snude (ikke en mus' spidse ansigt) — og meget mindre end en mosegris.",
    confusedWith: ["mosegris", "skovmus"],
    features: [
      "Small, stocky body with a short tail, small ears, and a blunt rounded snout — unlike a mouse's pointed face",
      "Greyish-brown fur, living in grassland and field edges under thick vegetation",
      "Makes visible surface runways through grass, rather than living mainly underground",
      "A key prey species for owls, foxes, and weasels",
    ],
  },
  {
    id: "mosegris",
    category: "gnavere",
    name_da: "Mosegris",
    name_en: "Water vole",
    latin: "Arvicola amphibius",
    images: ["/images/pattedyr/gnavere/mosegris_1.webp"],
    weight: "150–300 g",
    habitat: "soeer",
    activity: "both",
    rarity: 3,
    native: true,
    differentiator: "Samme stumpe ansigt som en markmus, men meget større, og lever ved vand i stedet for på tørre marker.",
    confusedWith: ["markmus", "rotte"],
    features: [
      "Much larger and stockier than a field vole, with a blunt face and small ears hidden in the fur",
      "Furry tail (not naked and scaly like a rat's), roughly half its body length",
      "Semi-aquatic, digging burrows into stream and pond banks",
      "Often mistaken for a rat, but rounder-faced and much less pointed at the nose",
    ],
  },
  {
    id: "skovmus",
    category: "gnavere",
    name_da: "Skovmus",
    name_en: "Wood mouse",
    latin: "Apodemus sylvaticus",
    images: ["/images/pattedyr/gnavere/skovmus.webp"],
    weight: "13–27 g",
    habitat: "loevskov",
    activity: "night",
    rarity: 1,
    native: true,
    differentiator: "Ægte mus med store øjne/ører og en hale lige så lang som kroppen — meget mindre end en rotte.",
    confusedWith: ["rotte", "markmus"],
    features: [
      "Small true mouse with large dark eyes and ears, and a tail about as long as its body",
      "Sandy-brown back with a clean white belly and a small yellowish chest patch",
      "Excellent jumper, common in gardens, fields, and woodland",
      "Much smaller and lighter than a rat, with a proportionally longer tail",
    ],
  },
  {
    id: "rotte",
    category: "gnavere",
    name_da: "Rotte",
    name_en: "Brown rat",
    latin: "Rattus norvegicus",
    images: ["/images/pattedyr/gnavere/rotte_1.webp"],
    weight: "200–500 g",
    habitat: "beboelse",
    activity: "night",
    rarity: 1,
    native: false,
    differentiator: "Meget større end skovmus og markmus, med en tyk, nøgen hale der er kortere end kroppen.",
    confusedWith: ["skovmus", "mosegris"],
    features: [
      "Much larger than any native mouse or vole, with a thick, scaly, naked tail shorter than its body",
      "Blunt nose, small ears, and a heavy, robust build",
      "Common around farms, waterways, sewers, and urban areas",
      "Highly adaptable omnivore, active mostly at night",
    ],
  },
  {
    id: "muldvarp",
    category: "gnavere",
    name_da: "Muldvarp",
    name_en: "European mole",
    latin: "Talpa europaea",
    images: ["/images/pattedyr/gnavere/muldvarp_1.webp"],
    weight: "70–130 g",
    habitat: "landbrugsland",
    activity: "both",
    rarity: 2,
    native: true,
    differentiator: "Cylindrisk, fløjlssort krop uden synlige ører — de skovlformede forpoter er umiskendelige.",
    confusedWith: [],
    features: [
      "Cylindrical, velvety black body built for tunneling, with no visible external ears",
      "Large, spade-like, outward-turned front paws for digging",
      "Tiny eyes mostly hidden by fur — spends almost its entire life underground",
      "Its molehills of loose soil are usually the only visible sign of it",
    ],
  },
  {
    id: "pindsvin",
    category: "gnavere",
    name_da: "Pindsvin",
    name_en: "European hedgehog",
    latin: "Erinaceus europaeus",
    images: ["/images/pattedyr/gnavere/pindsvin_1.webp"],
    weight: "400–1200 g",
    habitat: "beboelse",
    activity: "night",
    rarity: 2,
    native: true,
    differentiator: "Det piggede ryg og evnen til at rulle sig sammen er unikt — intet andet dansk dyr ligner den.",
    confusedWith: [],
    features: [
      "Entire back and sides covered in short, stiff spines; rolls into a ball when threatened",
      "Small pointed face and short legs, mostly nocturnal",
      "Snuffles noisily through leaf litter and garden undergrowth hunting insects and slugs",
      "Hibernates through the coldest months, often in piles of leaves or brush",
    ],
  },

  // --- Andet (wild boar and mouflon) ---
  {
    id: "vildsvin",
    category: "andet",
    name_da: "Vildsvin",
    name_en: "Wild boar",
    latin: "Sus scrofa",
    images: ["/images/pattedyr/andet/vildsvin_1.webp", "/images/pattedyr/andet/vildsvin_2.webp", "/images/pattedyr/andet/vildsvin_3.webp"],
    weight: "50–175 kg",
    habitat: "naaleskov",
    activity: "night",
    rarity: 4,
    native: true,
    differentiator: "Stort, kompakt og stridhåret — ornens store, opadrettede hugtænder kan ses i mundvigen selv på afstand; kan ikke forveksles med andre arter.",
    confusedWith: [],
    features: [
      "Large, compact, dark or brown animal with a coarse, bristly coat",
      "Boars are dark and compact with large upturned tusks, often visible at the corner of the mouth even at a distance — sows have smaller tusks and a less compact build",
      "Yearlings are often brown and smaller than the adults",
      "Boars 50–175 kg, sows considerably less; sows lead the herd (rotte), while old boars usually live alone",
    ],
  },
  {
    id: "muflon",
    category: "andet",
    name_da: "Muflon",
    name_en: "Mouflon",
    latin: "Ovis gmelini musimon",
    images: ["/images/pattedyr/andet/muflon_1.webp"],
    weight: "30–60 kg",
    habitat: "loevskov",
    activity: "day",
    rarity: 5,
    native: false,
    differentiator: "Vædderen har store, krumme horn og en lys sadelplet på ryggen — kun får og lam kan forveksles med då, sika og deres kalve.",
    confusedWith: ["daadyr", "sika"],
    features: [
      "Rams: large curved horns, and a brown to dark-brown coat with a clear pale saddle patch across the back",
      "Ewes: may have short horns but are often hornless, and are normally brown",
      "Rams 50–60 kg, ewes 30–45 kg",
      "Apart from a small free-living population in central Jutland and a few islands, mouflon in Denmark live only in fenced deer parks",
    ],
  },
];

export default SPECIES.map((s) => ({ ...s, images: s.images.map(asset) }));
